[[Installation]]
== Installation

The following list contains links to the sections that describe in detail how to download, install and activate Peach Fuzzer.

xref:Installation_Hardware[Recommended Hardware]::
  This section describes the minimum and recommended hardware requirements for common fuzzing scenarios.

xref:Installation_Download[Product Download]::
  This section contains the steps required to download the product for your desired platform.

Product Installation::
  This section lists the software prerequisites, OS specific configuration, and steps for installing the product on each of the three supported platforms:
  * xref:InstallOnWindows[Windows]
  * xref:InstallOnLinux[Linux]
  * xref:InstallOnOSX[OSX]

Product Activation::
  The list below contains links to the steps for activating the different types of Peach Fuzzer licenses.
  * xref:ActivateOnline[Usage Based (Online Synchronization)]
  * xref:ActivateOffline[Usage Based (Offline Synchronization)]
  * xref:ActivateNodeLock[Node Locked]
  * xref:ActivateEnterprise[Enterprise]

Optional Configuration::
  The list below contains links to optional post-install configurations.
  * xref:InstallSecureInstall[Enabling HTTPS And Authentication]

include::01_Hardware.adoc[]

include::02_Downloading.adoc[]

include::03_Windows.adoc[]

include::04_Linux.adoc[]

include::05_OSX.adoc[]

include::06_Activation.adoc[]

include::07_SecurePeach.adoc[]

// end
