[[InstallSecureInstall]]
=== Enabling HTTPS And Authentication

{product} uses a web interface for configuration and control of the fuzzing engine.
By default, the web interface is accessible with no encryption (SSL/TLS) and no authentication.
If the use of HTTPS or authentication is required, a reverse proxy (apache/nginx/traefik) can be used to provide both SSL/TLS and authentication.

==== Reverse Proxy with NGINX

The following steps will configure NGINX as a reverse proxy for Peach adding TLS and authentication:

. Install nginx using your Linux package manager
. Create required key.  For self signed keys this
link:http://www.selfsignedcertificate.com/[online self-signed certificate generator] can be used.
. Install the included NGINX configuration file to /etc/nginx/sites-available/peach
. Install certificate and key and update configuration file if needed
. Create .htpasswd with username/passwords replacing +USERNAME+ with your username
+
----
sudo sh -c "echo -n 'USERNAME:' >> /etc/nginx/.htpasswd"
sudo sh -c "openssl passwd -apr1 >> /etc/nginx/.htpasswd"
----

. Add a firewall rule to block external access to Peach's port 8888.  Make sure this rule is enabled on bootup.
. Link /etc/nginx/sites-available/peach to /etc/nginx/sites-enabled/peach
. Restart NGINX and verify configuration is working

===== NGINX Configuration File
----
# HTTPS server
#
server {
        listen 443;
        server_name localhost;

        root html;
        index index.html index.htm;

        ssl on;
        ssl_certificate /etc/ssl/certs/ssl.crt;
        ssl_certificate_key /etc/ssl/private/ssl.key;

        ssl_session_timeout 5m;

        ssl_protocols TLSv1.1 TLSv1.2;
        ssl_ciphers "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES";
        ssl_prefer_server_ciphers on;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                #try_files $uri $uri/ =404;
                # Uncomment to enable naxsi on this location
                # include /etc/nginx/naxsi.rules


                auth_basic "Restricted";
                auth_basic_user_file /etc/nginx/.htpasswd;
                proxy_pass http://127.0.0.1:8888/;
        }
}
----
