[[Program_Peach]]
== The {peachcomd}

This is the core Peach application which provides the core fuzzing capabilities and 
also some utility functions for the custom pit developer. 
This application can be used to start the Peach Web Application and 
also to launch fuzzing jobs from the command line.

Some options may be disabled depending on your Peach License options.

Please submit any bugs to support@peachfuzzer.com.

=== Peach Web Application

Starts Peach and provides a web application for configuring, running, and 
viewing results of a fuzzing job.

==== Syntax

----
peach [options]
----

--nobrowser::
    Disable launching browser on start.
--webport=PORT::
    Specified port the web application runs on.
--plugins=PATH::
    Change the plugins folder location. 
    Defaults to the 'Plugins' folder relative to the Peach installation.

=== Fuzzing from Command Line

A fuzzing run is started by specifying the Peach Pit Configuration or
Peach XML file and the name of a test to perform.

If a run is interrupted,
it can be restarted by providing the last successful test case and the seed of the test session.
Use the --skipto and --seed parameters to provide this information. 

==== Syntax

----
peach [options] <PEACH_PIT.xml | PEACH_CONFIG.peach> [test_name]
----

PEACH_CONFIG.peach::
    Peach Pit Configuration generated by Peach Application.
PEACH_PIT.xml::
    The Peach Pit XML file.
test_name::
    Name of test to run (defaults to 'Default').
-1::
    Perform a single test case
--debug::
    Enable debug messages. 
    Useful when debugging Peach Pit Files.
-DKEY=VALUE::
    Define a configuration variable via the command line. 
    Multiple defines can be provided as needed.
    Example: -DTargetIPv4=127.0.0.1 -DTargetPort=80
--duration=DUR::
    Duration of fuzzing run. Peach will run for DUR length of time. 
    Commonly integrating Peach into an automated test cycle or continuous integration environment. 
    Argument format is DD.HH:MM:SS.
    Examples;;
        * +--duration=12+     Duration of 12 days
        * +--duration=0:20+   Duration of 20 min
        * +--duration=5:00+   Duration of 5 hours
        * +--duration=1.5:00+ Duration of 1 day, 5 hrs
    
--noweb:: 
    Disable the Peach Web Application
--plugins=PATH::
    Change the plugins folder location. 
    Defaults to the 'Plugins' folder relative to the Peach installation.
--polite::
    Disable interactive console mode
--range=S,F::
    Perform a range of test cases starting at test case S and ending with test case F. 
    Typically combined with the --seed argument.
--seed=SEED::
    Set the fuzzing jobs seed. 
    The same seed will always produce the same test case sequence. 
    Should only be set when reproducing a historical fuzzing job. 
    Default is a random seed.
--skipto=NUM::
    Skip to NUM test case and start fuzzing. 
    Normally combined with --seed to reproduce a specific sequence of test cases.
--trace::
    Enable even more verbose debug messages.
--webport=PORT::
    Specified port the web application runs on

=== Debug Peach XML File

This will perform a single iteration (-1) of your pit file while 
displaying a lot of debugging information (--debug).
The debugging information is intended for custom pit developers.

==== Syntax

----
peach -1 --debug <PEACH_PIT.xml | PEACH_CONFIG.peach> [test_name]
----
 

=== Display List of Network Capture Devices

Display a list of all known devices Peach can perform network capture on.

==== Syntax

----
peach --showdevices
----

=== Display Known Elements

Print a list of all known: 

* Actions
* Agent Channels
* Analyzers
* DataElements
* Fixups
* Loggers
* Monitors
* Mutation Strategies
* Mutators
* Publishers
* Relations
* Transformers

The list includes any associated parameters along with a description and default values. 
This can be used to verify that custom extensions are found.

==== Syntax

---- 
peach --showenv
----

=== Peach Agent

The Peach Agent functionality has been moved to a separate executable. 
See xref:Program_PeachAgent[PeachAgent] for more information.

ifndef::peachug[]

=== Running Analyzers from Command Line

This functionality has been moved to a separate executable.
See xref:PitTool_Analyzer[PitTool - Analyzer] for more information.

=== Generate XML Schema File

This functionality has been moved to a separate executable.
See xref:PitTool_Makexsd[PitTool - Makexsd] for more information.

endif::peachug[]

=== Examples

.Running a Pit Configuration (.peach)
======================
This example shows how to run a fuzzing job from a configuration file (.peach). 
The following command line launches Peach and fuzzes using +pit_config.peach+ as the configuration file.

----
> peach pit_config.peach
----
======================

.Running a Pit
======================
This example shows how to run a fuzzing definition. 
The following command line launches Peach and fuzzes using +pit.xml+ (and if it exists, +pit.xml.config+) as the configuration file.

----
> peach pit.xml
----
======================

.Single Iteration with Debug Output
======================
When testing a definition, we recommend running a single non-mutating iteration with debug output.

The following command line launches Peach and fuzzes using +pit.xml+ (and if it exists, +pit.xml.config+) as the configuration file. 
The command line combines the +-1+ and +--debug+ arguments to run a single iteration; 
the debugging information is included in the output. 
Even more verbose output can be enabled by using +--trace+ instead of +--debug+.

----
> peach -1 --debug samples\DebuggerWindows.xml

[*] Test 'Default' starting with random seed 27886.
Peach.Core.Agent.Agent StartMonitor: Monitor WindowsDebugger
Peach.Core.Agent.Agent StartMonitor: Monitor_1 PageHeap
Peach.Core.Agent.Agent StartMonitor: Monitor_2 NetworkCapture
Peach.Core.Agent.Agent SessionStarting: Monitor
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid SessionStarting
Peach.Core.Agent.Agent SessionStarting: Monitor_1
Establishing the listener...
Waiting for a connection...
Peach.Core.Agent.Agent SessionStarting: Monitor_2

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.TcpClientPublisher start()
Peach.Core.Publishers.TcpClientPublisher open()
Accepted connection from 127.0.0.1:51466.
Peach.Core.Publishers.TcpClientPublisher output(12 bytes)
Peach.Core.Publishers.TcpClientPublisher

00000000   48 65 6C 6C 6F 20 57 6F  72 6C 64 21               Hello World!

Received 12 bytes from client.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.TcpClientPublisher output(12 bytes)
Peach.Core.Publishers.TcpClientPublisher

00000000   48 65 6C 6C 6F 20 57 6F  72 6C 64 21               Hello World!

Received 12 bytes from client.
Peach.Core.Publishers.TcpClientPublisher close()
Peach.Core.Publishers.TcpClientPublisher Shutting down connection to 127.0.0.1:4
244
Connection closed by peer.
Shutting connection down...
Connection is down.
Peach.Core.Publishers.TcpClientPublisher Read 0 bytes from 127.0.0.1:4244, closing client connection.
Waiting for a connection...
Peach.Core.Publishers.TcpClientPublisher Closing connection to 127.0.0.1:4244
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid DetectedFault()
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid DetectedFault() - No fault detected
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.TcpClientPublisher stop()
Peach.Core.Agent.Agent SessionFinished: Monitor_2
Peach.Core.Agent.Agent SessionFinished: Monitor_1
Peach.Core.Agent.Agent SessionFinished: Monitor
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid SessionFinished
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _StopDebugger
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _FinishDebugger
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _StopDebugger
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _StopDebugger
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _FinishDebugger
Peach.Core.Agent.Monitors.WindowsDebuggerHybrid _StopDebugger

[*] Test 'Default' finished.
----
======================

[[Replay_Existing_Test_Sequence]]
.Replay Existing Test Sequence
======================
Once you find a faulting condition,
you may want to replicate the exact test (or sequence of tests) to recreate the issue.
Peach can reproduce exact test sequences given the following information:

. Exact version of Peach. This is found in the log file +status.txt+.
. Seed number used. This is also found in the log file +status.txt+.
. Same/similar pit file. Data and state models must be the same.
. If datasets are used, they must be the same set and have the same contents.

.status.txt
----
Peach Fuzzing Run
=================

Date of run: 3/20/2014 1:58:58 PM
Peach Version: 3.1.40.1              <1>
Seed: 51816                          <2>
Command line: samples\DebuggerWindows.xml
Pit File: samples\DebuggerWindows.xml
. Test starting: Default

----
<1> Version of Peach used. Must match when reproducing.
<2> Seed used. Must match when reproducing.

We can use the first command line to skip directly to a specific iteration and start fuzzing. This lets you run a series of iterations starting from a certain point. 

TIP: The +--seed+ argument matches the value from the +status.txt+ file.

----
> peach --seed 51816 --skipto 37566
----

We can use the second command line to perform either a specific iteration or a small number of iterations.

----
> peach --seed 51816 --range 37566,37566
----

======================
