<<<
[[Action_infrag]]
== infrag

The _infrag_ action is a special action to perform fragemented input. It must be used inconjunction with a data model that contains the xref:Frag[Frag] element as it's first and only element. The _infrag_ action will utalize the fragmentation algorithm from the _Frag_ element to identify when to stop receiving fragments. One or more xref:Action_input[input] actions will be performed until the fragmentation algorithm is satisfied or a timeout occurs. Each _input_ action that occurs will crack incoming data into a copy of the _Frag_'s _Template_ element and added to the _Rendering_ sequence element.

Once all of the fragments have been received they will be reconstructed and cracked into the _Frag_ elements _Payload_ element. After the _infrag_ action has successfully been run values can be slurped from the _Payload_ element or the _Rendering_ sequence element.

See also: xref:Frag[Frag], xref:Action_outfrag[outfrag], xref:Action_input[input].

.Input Timeout
****
If the input time out is reached prior to all incoming data being received, Peach behaves as follows:

xref:Iteration_record[Timeout during a record iteration]::
When a record iteration generates errors, Peach assumes the environment is not working correctly or the pit is incorrect.   In both cases, fuzzing cannot continue.
Peach throws an exception and stops.

xref:Iteration_control[Timeout during a control iteration]::
Control iterations must be enabled to reach for this state.
Control iterations assume that any error is the result of the target entering an unwanted state. Peach triggers a fault.

xref:Iteration_fuzzing[Timeout during a fuzzing iteration]::
Peach continues fuzzing with the  next iteration. 
During normal fuzzing iterations, Peach assumes fuzzing causes odd behaviors from the target that are ignored, unless they occur during a control iteration.
****

.Default Order of Actions
****
The following is the default order in which Actions are performed when fuzzing:

. _start_ - Implicit, once per session
. _open_ - Implicit, once per iteration
. Explicit actions (such as _accept_, _input_, _infrag_, _output_ and _outfrag_)
. _close_ - Implicit, once per iteration
. _stop_ - Implicit, once per session
****

=== Syntax

[source,xml]
----
<StateModel name="TheStateModel" initialState="InitialState">
  <State name="InitialState"> 

    <Action type="infrag">
      <DataModel ref="ModelWithFragElement" />
    </Action>

  </State>
</StateModel>
----

=== Attributes

_Required:_

type:: Action type, must be set to "infrag"

_Optional:_

name:: Name used to identify the action
publisher:: Name of the publisher to perform this action
xref:Action_when[when]:: Perform action if the provided expression evaluates to true
xref:Action_onStart[onStart]:: Evaluate expression at the start of an action.
xref:Action_onComplete[onComplete]:: Evaluate expression upon completion of an action

=== Child Elements

xref:DataModel[DataModel]:: Reference to a DataModel that will receive cracked input data

=== Examples

.Receiving Input from TCP Publisher
==========================
A simple fragmented protocol in which each fragment has a single byte of payload data prefixed with the total length of data expected. The provided payload +example.txt+ contains 4 bytes of data resulting in 4 fragments.

.example.xml
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach	xmlns="http://peachfuzzer.com/2012/Peach" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

    <DataModel name="Fragmented">
        <Frag fragLength="1" totalLengthField="TotalLength">

            <Block name="Template">
                <String name="TotalLength" length="1"/>
                <Blob name="FragData" length="1" />
            </Block>

            <Block name="Payload">
                <String name="Value" />
            </Block>
        </Frag>
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="infrag">
				<DataModel ref="Fragmented"/>
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>
		<Publisher class="Tcp">
			<Param name="Host" value="127.0.0.1"/>
			<Param name="Port" value="6666"/>
		</Publisher>
	</Test>
</Peach>
----

.example.txt
----
4T4e4s4t
----

Prior to running Peach start a netcat listener using the following command line.  This will provide the fragments to Peach.

   nc -vv 127.0.0.1 6666 < example.txt

Run peach:

----
> peach -1 --debug example.xml

[*] Web site running at: http://10.0.1.87:8888/

[*] Test 'Default' starting with random seed 61424.
2016-07-07 16:59:13.0764 Peach.Pro.Core.Loggers.JobLogger Writing debug.log to: C:\peach-pro\output\win_x64_debug\bin\Logs\example.xml_20160707165911\debug.log

[R1,-,-] Performing iteration
2016-07-07 16:59:13.2186 Peach.Core.Engine runTest: Performing control recording iteration.
2016-07-07 16:59:13.2344 Peach.Pro.Core.Dom.Frag Generating fragments:
2016-07-07 16:59:13.2344 Peach.Core.Dom.StateModel Run(): Changing to state "Initial".
2016-07-07 16:59:13.2554 Peach.Core.Dom.Action Run(Action): Infrag
2016-07-07 16:59:13.2554 Peach.Pro.Core.Publishers.TcpClientPublisher start()
2016-07-07 16:59:13.2554 Peach.Pro.Core.Publishers.TcpClientPublisher open()
2016-07-07 16:59:13.2684 Peach.Pro.Core.Publishers.TcpClientPublisher input()
2016-07-07 16:59:13.2684 Peach.Pro.Core.Publishers.TcpClientPublisher Read 8 bytes from 127.0.0.1:6666
2016-07-07 16:59:13.2684 Peach.Pro.Core.Publishers.TcpClientPublisher

00000000   34 54 34 65 34 73 34 74                            4T4e4s4t

2016-07-07 16:59:13.2684 Peach.Pro.Core.Publishers.TcpClientPublisher Read 0 bytes from 127.0.0.1:6666, closing client connection.
2016-07-07 16:59:13.2684 Peach.Pro.Core.Publishers.TcpClientPublisher Closing connection to 127.0.0.1:6666
2016-07-07 16:59:13.2854 DataCracker -+ Block 'Frag_1', Bytes: 0/8, Bits: 0/64
2016-07-07 16:59:13.2964 DataCracker  | Size: ??? (Deterministic)
2016-07-07 16:59:13.2964 DataCracker  |-- String 'TotalLength', Bytes: 0/8, Bits: 0/64
2016-07-07 16:59:13.2964 DataCracker  |   Size: 1 bytes | 8 bits (Has Length)
2016-07-07 16:59:13.2964 DataCracker  |   Value: 4
2016-07-07 16:59:13.3135 DataCracker  |-- Blob 'FragData', Bytes: 1/8, Bits: 8/64
2016-07-07 16:59:13.3135 DataCracker  |   Size: 1 bytes | 8 bits (Has Length)
2016-07-07 16:59:13.3135 DataCracker  |   Value: 54
2016-07-07 16:59:13.3135 DataCracker  /
2016-07-07 16:59:13.3135 Peach.Pro.Core.Dom.Actions.Infrag Fragment 1: pos: 2 length: 8 crack consumed: 2 bytes <1>
2016-07-07 16:59:13.3135 Peach.Pro.Core.Publishers.TcpClientPublisher input()
2016-07-07 16:59:13.3135 DataCracker -+ Block 'Frag_2', Bytes: 2/8, Bits: 16/64
2016-07-07 16:59:13.3135 DataCracker  | Size: ??? (Deterministic)
2016-07-07 16:59:13.3135 DataCracker  |-- String 'TotalLength', Bytes: 2/8, Bits: 16/64
2016-07-07 16:59:13.3135 DataCracker  |   Size: 1 bytes | 8 bits (Has Length)
2016-07-07 16:59:13.3135 DataCracker  |   Value: 4
2016-07-07 16:59:13.3135 DataCracker  |-- Blob 'FragData', Bytes: 3/8, Bits: 24/64
2016-07-07 16:59:13.3135 DataCracker  |   Size: 1 bytes | 8 bits (Has Length)
2016-07-07 16:59:13.3135 DataCracker  |   Value: 65
2016-07-07 16:59:13.3135 DataCracker  /
2016-07-07 16:59:13.3135 Peach.Pro.Core.Dom.Actions.Infrag Fragment 2: pos: 4 length: 8 crack consumed: 2 bytes <2>
2016-07-07 16:59:13.3135 Peach.Pro.Core.Publishers.TcpClientPublisher input()
2016-07-07 16:59:13.3135 DataCracker -+ Block 'Frag_3', Bytes: 4/8, Bits: 32/64
2016-07-07 16:59:13.3135 DataCracker  | Size: ??? (Deterministic)
2016-07-07 16:59:13.3135 DataCracker  |-- String 'TotalLength', Bytes: 4/8, Bits: 32/64
2016-07-07 16:59:13.3135 DataCracker  |   Size: 1 bytes | 8 bits (Has Length)
2016-07-07 16:59:13.3135 DataCracker  |   Value: 4
2016-07-07 16:59:13.3135 DataCracker  |-- Blob 'FragData', Bytes: 5/8, Bits: 40/64
2016-07-07 16:59:13.3135 DataCracker  |   Size: 1 bytes | 8 bits (Has Length)
2016-07-07 16:59:13.3135 DataCracker  |   Value: 73
2016-07-07 16:59:13.3135 DataCracker  /
2016-07-07 16:59:13.3135 Peach.Pro.Core.Dom.Actions.Infrag Fragment 3: pos: 6 length: 8 crack consumed: 2 bytes <3>
2016-07-07 16:59:13.3135 Peach.Pro.Core.Publishers.TcpClientPublisher input()
2016-07-07 16:59:13.3135 DataCracker -+ Block 'Frag_4', Bytes: 6/8, Bits: 48/64
2016-07-07 16:59:13.3135 DataCracker  | Size: ??? (Deterministic)
2016-07-07 16:59:13.3135 DataCracker  |-- String 'TotalLength', Bytes: 6/8, Bits: 48/64
2016-07-07 16:59:13.3135 DataCracker  |   Size: 1 bytes | 8 bits (Has Length)
2016-07-07 16:59:13.3135 DataCracker  |   Value: 4
2016-07-07 16:59:13.3135 DataCracker  |-- Blob 'FragData', Bytes: 7/8, Bits: 56/64
2016-07-07 16:59:13.3135 DataCracker  |   Size: 1 bytes | 8 bits (Has Length)
2016-07-07 16:59:13.3135 DataCracker  |   Value: 74
2016-07-07 16:59:13.3135 DataCracker  /
2016-07-07 16:59:13.3135 Peach.Pro.Core.Dom.Actions.Infrag Fragment 4: pos: 8 length: 8 crack consumed: 2 bytes <4>
2016-07-07 16:59:13.3265 Peach.Pro.Core.Dom.Actions.Infrag Reassembled fragment is 4 bytes <5>
2016-07-07 16:59:13.3265 DataCracker -+ DataModel 'Fragmented', Bytes: 8/8, Bits: 64/64
2016-07-07 16:59:13.3265 DataCracker  | Size: ??? (Deterministic)
2016-07-07 16:59:13.3265 DataCracker  |-+ Frag 'DataElement_0', Bytes: 8/8, Bits: 64/64
2016-07-07 16:59:13.3265 DataCracker  | | Size: ??? (Deterministic)
2016-07-07 16:59:13.3265 DataCracker  | | Cracking Payload
2016-07-07 16:59:13.3265 DataCracker  | |-+ Block 'Payload', Bytes: 0/4, Bits: 0/32
2016-07-07 16:59:13.3265 DataCracker  | | | Size: ??? (Deterministic)
2016-07-07 16:59:13.3265 DataCracker  | | |-- String 'Value', Bytes: 0/4, Bits: 0/32
2016-07-07 16:59:13.3265 DataCracker  | | |   Size: 4 bytes | 32 bits (Last Unsized)
2016-07-07 16:59:13.3265 DataCracker  | | |   Value: Test
2016-07-07 16:59:13.3265 DataCracker  | | /
2016-07-07 16:59:13.3265 DataCracker  | /
2016-07-07 16:59:13.3265 DataCracker  /
2016-07-07 16:59:13.3265 Peach.Pro.Core.Dom.Actions.Infrag Final pos: 8 length: 8 crack consumed: 8 bytes
2016-07-07 16:59:13.3265 Peach.Pro.Core.Publishers.TcpClientPublisher close()
2016-07-07 16:59:13.3495 Peach.Core.Engine runTest: context.config.singleIteration == true
2016-07-07 16:59:13.3495 Peach.Pro.Core.Publishers.TcpClientPublisher stop()
2016-07-07 16:59:13.3495 Peach.Core.Engine EndTest: Stopping all agents and monitors

[*] Test 'Default' finished.

----
<1> First fragment cracked
<2> Second fragment cracked
<3> Third fragment cracked
<4> Forth and final fragment cracked
<5> Data reassembled and starting crack into Payload element.
==========================
