<<<
[[Action_outfrag]]
== outfrag

The _outfrag_ action is a special action to perform fragemented output. It must be used inconjunction with a data model that contains the xref:Frag[Frag] element as it's first and only element. The _outfrag_ action will perform multiple xref:Action_output[output] actions to send all the fragments in the _Rendering_ sequence collection. These fragments are generated by the fragmentation algorithm associated with the _Frag_ element.

See also: xref:Frag[Frag], xref:Action_infrag[infrag], xref:Action_output[output].

.Default Order of Actions
****
The following is the default order in which Actions are performed when fuzzing:

. _start_ - Implicit, once per session
. _open_ - Implicit, once per iteration
. Explicit actions (such as _accept_, _input_, _infrag_, _output_ and _outfrag_)
. _close_ - Implicit, once per iteration
. _stop_ - Implicit, once per session
****

=== Syntax

[source,xml]
----
<StateModel name="TheStateModel" initialState="InitialState">
  <State name="InitialState"> 

    <Action type="outfrag">
      <DataModel ref="ModelWithFragElement" />
    </Action>

  </State>
</StateModel>
----

=== Attributes

_Required:_

type:: Action type, must be set to "outfrag"

_Optional:_

name:: Name used to identify the action
publisher:: Name of the publisher to perform this action
xref:Action_when[when]:: Perform action if the provided expression evaluates to true
xref:Action_onStart[onStart]:: Evaluate expression at the start of an action.
xref:Action_onComplete[onComplete]:: Evaluate expression upon completion of an action

=== Child Elements

xref:DataModel[DataModel]:: Reference to a DataModel supplying data to fuzz
xref:Data[Data]:: Set of initial data to crack into the above DataModel before fuzzing

=== Examples

.Simple Example
==========================

Produce three fragments with each fragment contianing the current fragment lenght, fragement sequence and total length of data. The Payload is 30 bytes of 0x41.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

    <DataModel name="Fragmented">
        <Frag fragLength="10" 
              totalLengthField="TotalLength" 
              fragmentLengthField="FragLength" 
              fragmentIndexField="FragIndex">

            <Block name="Template">
                <Number name="FragLength" size="32"/>
                <Number name="FragIndex" size="32"/>
                <Number name="TotalLength" size="32"/>

                <Blob name="FragData" />
            </Block>

            <Block name="Payload">
                <Blob valueType="hex" value="
                    41 41 41 41 41 41 41 41 41 41
                    41 41 41 41 41 41 41 41 41 41
                    41 41 41 41 41 41 41 41 41 41"/>
            </Block>
        </Frag>
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="outfrag">
				<DataModel ref="Fragmented"/>
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>
		<Publisher class="ConsoleHex"/>
	</Test>
</Peach>
----

The example pit will produce three fragments with 10 bytes of payload per-fragment.

Output from this example:

----
>peach -1 --debug BoolExample1.xml

[*] Web site running at: http://10.0.1.87:8888/

[*] Test 'Default' starting with random seed 7010.
2016-07-07 14:26:22.2979 Peach.Pro.Core.Loggers.JobLogger Writing debug.log to: C:\peach-pro\output\win_x64_debug\bin\Logs\example.xml_20160707142621\debug.log

[R1,-,-] Performing iteration
2016-07-07 14:26:22.4288 Peach.Core.Engine runTest: Performing control recording iteration.
2016-07-07 14:26:22.4690 Peach.Pro.Core.Dom.Frag Generating fragments:
2016-07-07 14:26:22.4870 Peach.Core.Dom.StateModel Run(): Changing to state "Initial".
2016-07-07 14:26:22.4951 Peach.Core.Dom.Action Run(Action): Outfrag
2016-07-07 14:26:22.6139 Peach.Pro.Core.Publishers.ConsolePublisher start()
2016-07-07 14:26:22.6139 Peach.Pro.Core.Publishers.ConsolePublisher open()
2016-07-07 14:26:22.6188 Peach.Pro.Core.Publishers.ConsolePublisher output(22 bytes) <1>
00000000   0A 00 00 00 01 00 00 00  1E 00 00 00 41 41 41 41   ............AAAA
00000010   41 41 41 41 41 41                                  AAAAAA
2016-07-07 14:26:22.6188 Peach.Pro.Core.Publishers.ConsolePublisher output(22 bytes) <2>
00000000   0A 00 00 00 02 00 00 00  1E 00 00 00 41 41 41 41   ............AAAA
00000010   41 41 41 41 41 41                                  AAAAAA
2016-07-07 14:26:22.6188 Peach.Pro.Core.Publishers.ConsolePublisher output(22 bytes) <3>
00000000   0A 00 00 00 03 00 00 00  1E 00 00 00 41 41 41 41   ............AAAA
00000010   41 41 41 41 41 41                                  AAAAAA
2016-07-07 14:26:22.6188 Peach.Pro.Core.Publishers.ConsolePublisher close()
2016-07-07 14:26:22.6329 Peach.Core.Engine runTest: context.config.singleIteration == true
2016-07-07 14:26:22.6329 Peach.Pro.Core.Publishers.ConsolePublisher stop()
2016-07-07 14:26:22.6329 Peach.Core.Engine EndTest: Stopping all agents and monitors

[*] Test 'Default' finished.

----
<1> First fragment. Notice sequence number is 1.
<2> Second fragment. Notice sequence number is 2.
<3> Third fragment. Notice sequence number is 3.
==========================
