<<<
[[Action_output]]
== output

// 01/30/2014: Seth & Mike: Outlined
//  * Implicit actions when performing output
//  * Are multiple outputs different than single output?
//   * Answer: Mostly, no. But depends on publisher (Eg. udp, different packets. TCP, none. File, None.)
//  * Talk about multiple data sets
//  * Link to data sets
//  * Talk about single data model required
//  * Talk about scripting (when, onstart/complete)
//  * Talk about multiple publishers
//  * Talk about defining data model in action
//  * Name is optional
//  Examples with input/output as needed.
//  * Examples for talking points

// 02/12/2014: Mick
//  Added description of what Open does
//  talked about multiple actions in a row
//  talked about multiple data sets
//  talked about multiple publishers
//  Added attribute descriptions
//  Added an example

// 03/03/2014: Mike: Ready for tech writer
//  Updated description
//  Changed examples
//  Changed formatting
//  Reviewed output

// 03/05/2014: Lynn: 
//  Edited text

The _output_ action writes or sends data using a xref:Publisher[Publisher].
_output_ Actions are associated with a xref:DataModel[DataModel] (specified as a child element) that produces the data to be sent.

Along with a DataModel, data sets can be provided using the xref:Data[Data] element.
Multiple Data elements can be provided that are switched between during fuzzing depending on the fuzzing strategy used.
_Output_ actions are fuzzed by Peach.

When output is called, the fuzzer implicitly calls xref:Action_start[_start_] then xref:Action_open[_open_], if they have not yet been called.
If a Pit defines multiple publishers, the _publisher_ attribute specifies the publisher that performs the write/send request.
The exact behavior of an _output_ action is Publisher dependent. Review the documentation for a specific Publisher for details on its implementation actions. For example, calling output multiple times in succession on a stream publisher such as xref:Publishers_Tcp[TCP] appears in the logs as one output, whereas issuing multiple outputs in succession for the xref:Publishers_Udp[UDP] publisher sends the data as separate UDP Packets and lists in the logs as separate calls.

.Default Order of Actions
****
The following is the default order in which Actions are performed when fuzzing:

. _start_ - Implicit, once per session
. _open_ - Implicit, once per iteration
. Explicit actions (such as _accept_, _input_, and _output_)
. _close_ - Implicit, once per iteration
. _stop_ - Implicit, once per session
****

=== Syntax

[source,xml]
----
<StateModel name="TheStateModel" initialState="InitialState">
  <State name="InitialState">
    <Action type="output">
       <DataModel ref="SomeDataModel" />
    </Action>

    <Action type="output">
       <DataModel ref="SomeDataModel" />
       <Data name="SomeSampleData" fileName="sample.bin" />
    </Action>
  </State>
</StateModel>
----

=== Attributes

_Required:_

type:: Action type, must be set to "output"

_Optional:_

name:: Name used to identify the action
publisher:: Name of the publisher to perform this action
xref:Action_when[when]:: Perform the action if the provided expression evaluates to true
xref:Action_onStart[onStart]:: Evaluate expression at the start of an action.
xref:Action_onComplete[onComplete]:: Evaluate expression upon completion of an action

=== Child Elements

xref:DataModel[DataModel]:: Reference to a DataModel supplying data to fuzz
xref:Data[Data]:: Set of initial data to crack into the above DataModel before fuzzing

=== Examples

.File fuzzing with _output_ action
================================
Example of using the _output_ action with multiple data sets to perform file fuzzing.
This is a typical configuration for dumb file fuzzing.

Notice the special publisher _Peach.Agent_.
This publisher sends the _call_ action to all Agents, who in turn, forward the _call_  to each associated Monitor.
The method call is handled by the WindowsDebugger monitor, causing it to launch _notepad.exe_.
For file fuzzing, note that the target is launched after creating the new fuzzed file.

This example runs on the Windows(R) Operating System, version XP or newer, with Windows Debugging Tools installed.

. Save example Pit as "example.xml"
. Run "Peach.exe --range 1,10 --debug example.xml"
. You should see _mspaint.exe_ open and close several times.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">
  
  <DataModel name="DumbModel">
    <Blob />
  </DataModel>
  
  <StateModel name="State" initialState="Initial">
    <State name="Initial">
      
      <Action type="output">
        <DataModel ref="DumbModel" />

		<!-- provide a folder of files to fuzz -->
		<Data fileName="##Peach.Pwd##\samples_png" />
      </Action>
      
      <!-- Close file -->
      <Action type="close" />
      
      <!-- Launch the file consumer -->
      <Action type="call" method="ScoobySnacks" publisher="Peach.Agent"/>
      
    </State>
  </StateModel>
  
  <Agent name="LocalAgent">
    <Monitor class="WindowsDebugger">
      <Param name="Executable" value="c:\windows\system32\mspaint.exe />
      <Param name="Arguments" value="fuzzed.png" />
      <Param name="StartOnCall" value="ScoobySnacks" />
    </Monitor>
  </Agent>
  
  <Test name="Default">
    <Agent ref="LocalAgent" />
    <StateModel ref="State"/>
    
    <Publisher class="File">
      <Param name="FileName" value="fuzzed.png" />
    </Publisher>
  </Test>
  
</Peach>
----
================================

.Sending Output with TCP Publisher
==========================
This example uses the _output_ action to send data. Netcat (nc) is used in this example as the client.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <!-- Marking the string as a token will imply a length of 4 characters -->
  <DataModel name="Ping">
    <String value="PING" token="true"/>
  </DataModel>

  <DataModel name="Pong">
    <String value="PONG" />
  </DataModel>

  <StateModel name="TheStateModel" initialState="InitialState">
    <State name="InitialState">
      <Action type="accept" />

      <Action type="input">
        <DataModel ref="Ping"/> 
      </Action> 

      <Action type="output">
        <DataModel ref="Pong"/>
      </Action> 
    </State> 
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheStateModel"/>
    
    <Publisher class="TcpListener">
      <Param name="Interface" value="0.0.0.0" />
      <Param name="Port" value="31337" />
      <Param name="AcceptTimeout" value="10000" />
      <Param name="Timeout" value="10000" />
    </Publisher>

    <Logger class="File" >
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----

Output from this example. Once Peach is started, use the netcat command line to recreate output. Type the following command line and press RETURN to start netcat.

nc -vv 127.0.0.1 31337


----
> peach -1 --debug example.xml

[*] Test 'Default' starting with random seed 32331.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Accept
Peach.Core.Publishers.TcpListenerPublisher start()
Peach.Core.Publishers.TcpListenerPublisher open()
Peach.Core.Publishers.TcpListenerPublisher accept()
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Input
Peach.Core.Publishers.TcpListenerPublisher input()                           <1>
Peach.Core.Publishers.TcpListenerPublisher Read 5 bytes from 127.0.0.1:62407
Peach.Core.Publishers.TcpListenerPublisher

00000000   50 49 4E 47 0A                                     PING.

Peach.Core.Cracker.DataCracker ------------------------------------          <2>
Peach.Core.Cracker.DataCracker DataModel 'Ping' Bytes: 0/5, Bits: 0/40
Peach.Core.Cracker.DataCracker getSize: -----> DataModel 'Ping'
Peach.Core.Cracker.DataCracker scan: DataModel 'Ping'
Peach.Core.Cracker.DataCracker scan: String 'Ping.DataElement_0' -> Pos: 0, Saving Token
Peach.Core.Cracker.DataCracker scan: String 'Ping.DataElement_0' -> Pos: 32, Length: 32
Peach.Core.Cracker.DataCracker getSize: <----- Deterministic: ???
Peach.Core.Cracker.DataCracker Crack: DataModel 'Ping' Size: <null>, Bytes: 0/5, Bits: 0/40
Peach.Core.Cracker.DataCracker ------------------------------------
Peach.Core.Cracker.DataCracker String 'Ping.DataElement_0' Bytes: 0/5, Bits: 0/40
Peach.Core.Cracker.DataCracker getSize: -----> String 'Ping.DataElement_0'
Peach.Core.Cracker.DataCracker scan: String 'Ping.DataElement_0' -> Pos: 0, Saving Token
Peach.Core.Cracker.DataCracker scan: String 'Ping.DataElement_0' -> Pos: 32, Length: 32
Peach.Core.Cracker.DataCracker getSize: <----- Size: 32
Peach.Core.Cracker.DataCracker Crack: String 'Ping.DataElement_0' Size: 32, Bytes: 0/5, Bits: 0/40
Peach.Core.Dom.DataElement String 'Ping.DataElement_0' value is: PING
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.TcpListenerPublisher output(4 bytes)
Peach.Core.Publishers.TcpListenerPublisher

00000000   50 4F 4E 47                                        PONG

Peach.Core.Publishers.TcpListenerPublisher close()
Peach.Core.Publishers.TcpListenerPublisher Shutting down connection to 127.0.0.1:62407
Peach.Core.Publishers.TcpListenerPublisher Read 0 bytes from 127.0.0.1:62407, closing client connection.
Peach.Core.Publishers.TcpListenerPublisher Closing connection to 127.0.0.1:62407

Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.TcpListenerPublisher stop()

[*] Test 'Default' finished.
----
<1> Data received by TCP publisher
<2> Debugging output from the data cracker

Netcat command line. Once Netcat is running, type "PING" in upper case letters and press RETURN. Peach responds with "PONG".

----
> nc -vv 127.0.0.1 31337
Connection to 127.0.0.1 31337 port [tcp/*] succeeded!
PING
PONG
----
==========================

.Multiple Publishers with _output_ Action
================================
This example uses the _output_ action with multiple publishers to write two files out on every iteration.

. Save example Pit as "example.xml"
. Run "Peach.exe -1 --debug example.xml"
. You should see two files, fuzzed1.txt and fuzzed2.txt, created.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">
  
  <DataModel name="File1Model">
    <String value="I'm file #1" />
  </DataModel>
  
  <DataModel name="File2Model">
    <String value="I'm file #2" />
  </DataModel>
  
  <StateModel name="State" initialState="Initial">
    <State name="Initial">
      
      <Action type="output" publisher="File1">
        <DataModel ref="File1Model" />
      </Action>
      
      <Action type="output" publisher="File2">
        <DataModel ref="File2Model" />
      </Action>
      
    </State>
  </StateModel>
  
  <Test name="Default">
    <StateModel ref="State"/>
    
    <Publisher name="File1" class="File">
      <Param name="FileName" value="fuzzed1.txt" />
    </Publisher>

    <Publisher name="File2" class="File">
      <Param name="FileName" value="fuzzed2.txt" />
    </Publisher>
  </Test>
  
</Peach>
----
================================
