<<<
[[Action_setProperty]]
== setProperty

// 01/30/2014: Seth & Mike: Outlined
//  * Talk about setting values on publishers
//  * Talk about what properties are
//  * Talk about some of the publishers that use them (COM)
//  * Talk about data sets
//  * Set property is mutated (data is going out from peach)
//  Examples

// 02/12/2014: Mick
//  Added description of what setProperty does
//  talked about publishers that use it
//  Added attribute descriptions
//  Added an example

// 02/28/2014: Mike: Ready for tech review
//  Made content match getProperty
//  Ditto with examples

// 03/05/2014: Lynn: 
//  Edited text and corrected Apple QuickTime information

The _setProperty_ Action allows Peach to modify values of properties in the target or to modify properties of a Publisher while fuzzing. _setProperty_ Actions specify the xref:DataModel[DataModel] property in the target that receives fuzzing.

_setProperty_ provides one half of a property metaphor in Peach state models. _setProperty_ actions are considered output actions. xref:Action_getProperty[_getProperty_] is the other half (input) of the property metaphor.

Properties that are modified receive fuzzing in the same way an output action would be. 
For example, a test target, such as a COM object, can have a property set and mutated by Peach, as in the following example. 

The second use, setting and mutating a property in a publisher, is fuzzing the MTU attribute of the xref:Publishers_RawEther[RawEther] Publisher. Some Publishers support the use of properties.

NOTE: If you do not want to fuzz a property that is set using _setProperty_, set the mutable attribute of the data item to false. The item declaration is located in the DataModel.

.Default Order of Actions
****
The following is the default order in which Actions are performed when fuzzing:

. _start_ - Implicit, once per session
. _open_ - Implicit, once per iteration
. Explicit actions (_accept_, _input_, _output_, etc.)
. _close_ - Implicit, once per iteration
. _stop_ - Implicit, once per session
****

=== Syntax

[source,xml]
----
<StateModel name="TheStateModel" initialState="InitialState">
	<State name="InitialState">
		<Action type="setProperty" property="Name">
			<DataModel ref="NameModel"/>
		</Action>
	</State>
</StateModel>
----

=== Attributes

_Required:_

type:: Action type, must be set to "setProperty"

_Optional:_

name:: Name used to identify the action
property:: Name of property to set in the fuzzing target, or in the publisher
publisher:: Name of the publisher to perform this action, or the Name publisher with the property to modify
xref:Action_when[when]:: Perform action if the provided expression evaluates to true
xref:Action_onStart[onStart]:: Evaluate expression at the start of an action
xref:Action_onComplete[onComplete]:: Evaluate expression upon completion of an action

=== Child Elements

xref:DataModel[DataModel]:: Reference to a DataModel containing data to fuzz
xref:Data[Data]:: Set of initial data crack into the above DataModel before fuzzing

=== Examples

.Accessing a Property using Microsoft COM Publisher
==========================
This example fuzzes property values of a QuickTime COM object.
_setProperty_ sets the height of the player window.
Since _setProperty_ is considered data output, it is fuzzed.

This example requires a machine with the Windows Operating System, version XP or newer,   with Apple QuickTime installed.

. Start QuickTime
. Save example to "example.xml"
. Run "Peach.Core.ComContainer.exe"
. Run "Peach.exe -1 --debug example.xml"
. You should see the QuickTime movie start to play

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <!-- Import python module so we can sleep after saying play -->
  <Import import="time"/>
  
  <DataModel name="TheDataModel">
    <String name="Value" />
  </DataModel>
  
  <StateModel name="TheState" initialState="Initial">
    
    <State name="Initial">

      <Action type="call" method="Players[1].OpenURL">
        <!-- This parameter will be fuzzed -->
        <Param name="P1">
          <DataModel ref="TheDataModel" />
          
          <Data>
            <Field name="Value" value="https://archive.org/download/AppleComputersQuicktimeSample/sample.mp4"/>
          </Data>
        </Param>
      </Action>
      
      <!-- This property will be fuzzed -->
      <Action type="setProperty" property="Players[1].Height">
        <DataModel ref="TheDataModel" />
        <Data>
          <Field name="Value" value="100" />
        </Data>
      </Action>
      
      <!-- The onComplete expression will pause the fuzzer to let
           the video play for 6 seconds. -->
      <Action type="call" method="Players[1].QTControl.Movie.Play" onComplete="time.sleep(6)"/>

    </State>
    
  </StateModel>
  
  <Test name="Default">
    <StateModel ref="TheState"/>

    <Publisher class="Com">
      <Param name="clsid" value="QuickTimePlayerLib.QuickTimePlayerApp"/>
    </Publisher>
  </Test>
  
</Peach>
----
==========================
