<<<
[[Action_slurp]]
== slurp

// 01/30/2014: Seth & Mike: Outlined
//  * Talk about what slurp is and does
//  * Why would you want that?
//  * Talk about data models getting reset on state entry (or re-entry?)
//  * Talk about xpaths
//  * Link to stuff about xpaths
//  * Talk about using unique names to assist in using it
//  * Can't slurp container to container
//  * Only element to element
//  * If setXpath does not return any elements we will:
//   * Error on record, fault on control, ignore on mutation
//  * If valueXpath does not return single element we will:
//   * Error on record, fault on control, ignore on mutation
//  * If valueXpath returns same single element as setXpath:
//   * Error on record, fault on control, ignore on mutation
//  * Examples!

// 02/12/2014: Jordyn
//  Added description of what slurp does
//  talked about xpath values
//  Added attribute descriptions
//  Added an example

// 02/20/2013: Mike: Reviewed
//  * Verify examples still work
//  * Discuss setting a single element vs. many
//  * Discuss wildcard (//) vs. (/)

// 03/03/2014: Mike: Ready for tech review
//  Some minor updates
//  Still needs expanding, but push to next rev

// 03/05/2014: Lynn:
//  Rewrote definition text

Slurp moves data between two DataModels. The Slurp Action copies a data value from one non-container element in one DataModel to another non-container element in a separate DataModel.

A non-container element is an element that does not contain other elements. Number, string, and blob are types of non-container elements. In contrast, array, xref:Block[Block], xref:Choice[Choice], and xref:DataModel[DataModel]) are types of container elements.

* The xref:xpath[valueXpath] attribute defines the input element. The data model and the element in valueXpath were previously referenced by a prior input action.

* The xref:xpath[setXpath] attribute defines the output element.  The data model and the element in setXpath will be referenced by a future action.

The XML Path (XPath) language is used by valueXpath and setXpath to specify the data to move. XPath targets a specific element for the xref:xpath[valueXpath] and xref:xpath[setXpath] parameters. This allows a variety of ways to access these elements in the Document Object Model (DOM).

A common use for slurp is during a protocol sequence where a sequence id or a challenge id needs to round-trip from the server to the client and back to the server (see the Challenge Response example below). The _slurp_ Action copies the data received from the server (valueXpath attribute) into the response packet (setXpath attribute). When the response packet is populated, it is sent back to the server using another Action.

Potential Slurp errors include the following:

* Copying from a container element or copying to a container element (Copying is restricted to simple types, such as number, string, or blob.)
* The valueXpath parameter does not return a single element (One element is required; no more; no less. If you need to move more than one set of data, issue multiple slurp commands.)
* The valueXpath and setXpath parameters return the same element
* The setXpath parameter does not return any elements (The element has no content or the path is non-existent.)

Assigning unique names to elements simplifies targeting those elements with the valueXpath and setXpath attributes. Using XPath wildcards with unique element names allows an element to be targeted using its name instead of using the full path to the element. See the following examples for slurp actions with and without unique element names.

.XPath Further Reading
****
The following links provide additional information regarding XPath.

 * http://www.w3schools.com/xpath/[XPath Tutorial]
 * http://www.w3schools.com/xpath/xpath_syntax.asp[XPath Syntax]
 * http://www.w3.org/TR/xpath/[XPath Specification]

****

=== Syntax

[source,xml]
----
<DataModel name="ReceiveChallenge">
  <String name="Challenge" />
</DataModel>

<DataModel name="SendChallenge">
  <String name="Challenge" />
</DataModel>

<StateModel name="TheStateModel" initialState="InitialState">
	<State name="InitialState">
		<Action name="ReceiveChallenge" type="input">
			<DataModel name="TheReceiveChallenge" ref="ReceiveChallenge"/>
		</Action>

		<Action type="slurp" valueXpath="//TheReceiveChallenge/Challenge" setXpath="//TheSendChallenge/Challenge" />

		<Action name="SendChallenge" type="output">
			<DataModel name="TheSendChallenge" ref="SendChallenge"/>
		</Action>
	</State>
</StateModel>
----

=== Attributes

_Required:_

type:: Action type, must be set to "slurp"

_Optional:_

name:: Name used to identify the action
xref:xpath[valueXpath]:: Path to the source element. Must evaluate to match a single element.
xref:xpath[setXpath]:: Path to the destination element. Can match multiple elements on which to set the value.
xref:Action_when[when]:: Perform action if the provided expression evaluates to true
xref:Action_onStart[onStart]:: Evaluate expression to run at the start of an action
xref:Action_onComplete[onComplete]:: Evaluate expression upon completion of an action

=== Child Elements

None.

=== Examples

.Non-unique Names
==========================
This example uses fully specified names in the xpath query to identify elements.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="Ping">
    <String name="PingStr" value="Stop Copying Me" token="true"/>
  </DataModel>

  <DataModel name="Pong">
    <String name="Resp" value="I am not" />
  </DataModel>

  <StateModel name="TheStateModel" initialState="InitialState">
    <State name="InitialState">
      <Action name="PingPacket" type="input">
        <DataModel ref="Ping"/>
      </Action>

      <Action type="slurp" valueXpath="//PingPacket/Ping/PingStr" setXpath="//PongPacket/CopyResponse/Resp" />

      <Action name="PongPacket" type="output">
        <DataModel name="CopyResponse" ref="Pong"/>
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheStateModel"/>
    <Publisher class="Udp">
      <Param name="Host" value="127.0.0.1" />
      <Param name="SrcPort" value="1234" />
      <Param name="Timeout" value="10000" />
    </Publisher>

    <!-- Test with following command -->
    <!-- echo -n "Stop Copying Me" | nc -4u -w1 localhost 1234 -->

    <Strategy class="Random"/>

    <Logger class="File" >
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----
==========================

.Unique Names
==========================
This example uses unique names for the source element (input) and for the destination element (output) involved in the slurp.
Having unique names allows the simpler xpath notation that uses wildcards (//) instead of using a full name.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

	<DataModel name="Ping">
		<String name="PingStr" value="Stop Copying Me" token="true"/>
	</DataModel>

	<DataModel name="Pong">
		<String name="Resp" value="I am not" />
	</DataModel>

	<StateModel name="TheStateModel" initialState="InitialState">
		<State name="InitialState">
			<Action name="PingPacket" type="input">
				<DataModel ref="Ping"/>
			</Action>

			<Action type="slurp" valueXpath="//PingStr" setXpath="//Resp" />

			<Action name="PongPacket" type="output">
				<DataModel name="CopyResponse" ref="Pong"/>
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheStateModel"/>
		<Publisher class="Udp">
			<Param name="Host" value="127.0.0.1" />
			<Param name="SrcPort" value="1234" />
			<Param name="Timeout" value="10000" />
		</Publisher>

		<!-- Test with following command -->
		<!-- echo -n "Stop Copying Me" | nc -4u -w1 localhost 1234 -->

		<Strategy class="Random"/>

		<Logger class="File" >
			<Param name="Path" value="logs"/>
	    </Logger>
	</Test>
</Peach>
----
==========================

.Setting Multiple Elements
==========================
This example copies a value to multiple elements at once.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="Ping">
    <String name="PingStr" value="Stop Copying Me" token="true"/>
  </DataModel>

  <DataModel name="Pong">
    <String name="Resp" value="I am not" />
  </DataModel>

  <StateModel name="TheStateModel" initialState="InitialState">
    <State name="InitialState">
      <Action type="input">
        <DataModel ref="Ping"/>
      </Action>

      <!-- Will copy value from our input action to all of our output actions. -->
      <Action type="slurp" valueXpath="//PingStr" setXpath="//Resp" />

      <Action type="output">
        <DataModel ref="Pong"/>
      </Action>

      <Action type="output">
        <DataModel ref="Pong"/>
      </Action>

      <Action type="output">
        <DataModel ref="Pong"/>
      </Action>

      <Action type="output">
        <DataModel ref="Pong"/>
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheStateModel"/>
    <Publisher class="Udp">
      <Param name="Host" value="127.0.0.1" />
      <Param name="SrcPort" value="1234" />
      <Param name="Timeout" value="10000" />
    </Publisher>

    <!-- Test with following command -->
    <!-- echo -n "Stop Copying Me" | nc -4u -w1 localhost 1234 -->

    <Strategy class="Random"/>

    <Logger class="File" >
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----
==========================

.Challenge Response
==========================
This example shows how to use slurp for round-tripping a challenge id just issued by a server in the next response packet to the server.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="ReceiveChallenge">
    <String name="Challenge" />
  </DataModel>

  <DataModel name="SendChallenge">
    <String name="Challenge" />
  </DataModel>

  <StateModel name="TheStateModel" initialState="InitialState">
    <State name="InitialState">
      <Action name="ReceiveChallenge" type="input">
        <DataModel name="TheReceiveChallenge" ref="ReceiveChallenge"/>
      </Action>

      <Action type="slurp" valueXpath="//TheReceiveChallenge/Challenge" setXpath="//TheSendChallenge/Challenge" />

      <Action name="SendChallenge" type="output">
        <DataModel name="TheSendChallenge" ref="SendChallenge"/>
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheStateModel"/>
    <Publisher class="Udp">
      <Param name="Host" value="127.0.0.1" />
      <Param name="SrcPort" value="1234" />
      <Param name="Timeout" value="10000" />
    </Publisher>

    <!-- Test with following command -->
    <!-- echo -n "Stop Copying Me" | nc -4u -w1 localhost 1234 -->

    <Strategy class="Random"/>

    <Logger class="File" >
      <Param name="Path" value="logs"/>
      </Logger>
  </Test>
</Peach>
----
==========================
