<<<
[[Action_start]]
== start

// 01/30/2014: Seth & Mike: Outlined
//   * What is it?
//   * Implicit action
//    * When is it called?
//    * When would it be used explicitly?
//   * Examples

// 02/12/2014: Jordyn
//   Added description of what Start does
//   talked about using it explicitly
//   Added attribute descriptions
//   Added an example

// 02/27/2014: Mike: Ready for tech writer.

// 03/05/2014: Lynn: 
//  Edited and corrected definition text 

The _start_ action causes a xref:Publisher[Publisher] to perform the initialization that usually occurs at the start of a fuzzing session. _start_ normally occurs once per fuzzing session, at the start of session. Another Action element, xref:Action_stop[_stop_], also normally occurs once per fuzzing session, at the end of the session. 

_start_ is an implicit Peach action that should not be declared in the xref:StateModel[StateModel] unless a change is needed in the default behavior.

*NOTE:* Including the _start_ or _stop_ action in the StateModel causes the action to run every iteration instead of once per session. This declaration should be avoided unless specifically required.

Not all xref:Publisher[Publishers] make use of _start_ and _stop_.

.Default Order of Actions
****
The following is the default Actions order when fuzzing:

. _start_ - Implicit, once per session
. _open_ - Implicit, once per iteration
. Explicit actions (such as _accept_, _input_ and _output_)
. _close_ - Implicit, once per iteration
. _stop_ - Implicit, once per session
****

=== Syntax

[source,xml]
----
<StateModel name="TheStateModel" initialState="InitialState">
	<State name="InitialState">
		<Action type="start" />
	</State>
</StateModel>
----

=== Attributes

_Required:_

type:: Action type, must be set to "start"

_Optional:_

name:: Name used to identify the action
publisher:: Name of the publisher to perform this action
xref:Action_when[when]:: Only perform the action if the provided expression evaluates to true
xref:Action_onStart[onStart]:: Expression to run at the start of an action.
xref:Action_onComplete[onComplete]:: Expression to run at the completion of an action

=== Child Elements

None.

=== Examples

.Default behavior
==========================
The Example Pit shows normal (default) behavior.
Declarations for _start_ and _stop_ are unnecessary and not included.
The output follows the Pit definition.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="Ping">
    <String value="PING" token="true"/>
  </DataModel>

  <StateModel name="TheStateModel" initialState="InitialState">
    <State name="InitialState">

      <!-- Start action is implicitly called once per session by Peach.
           It will cause the Publisher to perform any initialization. -->

      <!-- Open action is implicitly called on every iteration by Peach.
           It will cause the Publisher to open a connection to the remote host. -->

      <!-- This action is called on every iteration. It will output data from
           the data model "Ping" using our Publisher. -->
      <Action type="output">
        <DataModel ref="Ping"/>
      </Action>

      <!-- Close action is implicitly called on every iteration by Peach.
           It will cause the Publisher to close its connection to the remote
           host if it's still open. -->

      <!-- This action is implicitly called once per fuzzing session. It will perform any
           final clean up actions to fully stop the Publisher. -->

    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheStateModel"/>
    <Publisher class="Tcp">
      <Param name="Host" value="127.0.0.1" />
      <Param name="Port" value="31337" />
    </Publisher>

    <Logger class="File" >
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----

Output showing the default behavior of the sample pit where the _start_ action is called once at the beginning of the fuzzing session and the _stop_ action is called once at the end of the fuzzing session.

----
> peach --range 1,3 --seed 51405 example.xml

[[ Peach Professional v3.0.0
[[ Copyright (c) Peach Fuzzer LLC
Peach.Core.Engine runTest: context.config.range == true, start: 1, stop: 3

[*] Test 'Default' starting with random seed 51405.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.TcpClientPublisher start()                             <1>
Peach.Core.Publishers.TcpClientPublisher open()
Peach.Core.Publishers.TcpClientPublisher output(4 bytes)
Peach.Core.Publishers.TcpClientPublisher

00000000   50 49 4E 47                                        PING

Peach.Core.Publishers.TcpClientPublisher close()
Peach.Core.Publishers.TcpClientPublisher Shutting down connection to 127.0.0.1:31337
Peach.Core.Publishers.TcpClientPublisher Read 0 bytes from 127.0.0.1:31337, closing client connection.
Peach.Core.Publishers.TcpClientPublisher Closing connection to 127.0.0.1:31337

[1,3,0:00:01.614] Performing iteration
[*] Fuzzing: Ping.DataElement_0
[*] Mutator: DataElementSwapNearNodesMutator
Peach.Core.MutationStrategies.RandomStrategy Action_Starting: Fuzzing: Ping.DataElement_0
Peach.Core.MutationStrategies.RandomStrategy Action_Starting: Mutator: DataElementSwapNearNodesMutator
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.TcpClientPublisher open()
Peach.Core.Publishers.TcpClientPublisher output(4 bytes)
Peach.Core.Publishers.TcpClientPublisher

00000000   50 49 4E 47                                        PING

Peach.Core.Publishers.TcpClientPublisher close()
Peach.Core.Publishers.TcpClientPublisher Shutting down connection to 127.0.0.1:31337
Peach.Core.Publishers.TcpClientPublisher Read 0 bytes from 127.0.0.1:31337, closing client connection.
Peach.Core.Publishers.TcpClientPublisher Closing connection to 127.0.0.1:31337

[2,3,0:00:03.438] Performing iteration
[*] Fuzzing: Ping.DataElement_0
[*] Mutator: UnicodeUtf8ThreeCharMutator
Peach.Core.MutationStrategies.RandomStrategy Action_Starting: Fuzzing: Ping.DataElement_0
Peach.Core.MutationStrategies.RandomStrategy Action_Starting: Mutator: UnicodeUtf8ThreeCharMutator
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.TcpClientPublisher open()
Peach.Core.Publishers.TcpClientPublisher output(522 bytes)
Peach.Core.Publishers.TcpClientPublisher

00000000   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000010   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000020   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
00000030   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000040   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000050   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
00000060   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000070   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000080   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
00000090   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
000000A0   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
000000B0   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
000000C0   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
000000D0   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
000000E0   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
000000F0   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000100   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000110   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
00000120   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000130   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000140   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
00000150   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000160   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000170   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
00000180   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000190   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
000001A0   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
000001B0   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
000001C0   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
000001D0   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
000001E0   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
000001F0   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000200   B0 EF 83 B0 EF 83 B0 EF  83 B0                     ..........

Peach.Core.Publishers.TcpClientPublisher close()
Peach.Core.Publishers.TcpClientPublisher Shutting down connection to 127.0.0.1:31337
Peach.Core.Publishers.TcpClientPublisher Read 0 bytes from 127.0.0.1:31337, closing client connection.
Peach.Core.Publishers.TcpClientPublisher Closing connection to 127.0.0.1:31337

[3,3,0:00:01.454] Performing iteration
[*] Fuzzing: Ping.DataElement_0
[*] Mutator: UnicodeUtf8ThreeCharMutator
Peach.Core.MutationStrategies.RandomStrategy Action_Starting: Fuzzing: Ping.DataElement_0
Peach.Core.MutationStrategies.RandomStrategy Action_Starting: Mutator: UnicodeUtf8ThreeCharMutator
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.TcpClientPublisher open()
Peach.Core.Publishers.TcpClientPublisher output(1968 bytes)
Peach.Core.Publishers.TcpClientPublisher

00000000   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000010   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000020   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
00000030   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000040   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000050   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
00000060   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000070   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000080   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
....

Peach.Core.Publishers.TcpClientPublisher close()
Peach.Core.Publishers.TcpClientPublisher Shutting down connection to 127.0.0.1:31337
Peach.Core.Publishers.TcpClientPublisher Read 0 bytes from 127.0.0.1:31337, closing client connection.
Peach.Core.Publishers.TcpClientPublisher Closing connection to 127.0.0.1:31337
Peach.Core.Publishers.TcpClientPublisher stop()                              <2>

[*] Test 'Default' finished.
----
<1> _Start_ action at beginning of fuzzing session
<2> _Stop_ action at end of fuzzing session

==========================

.Explicit calling of start
==========================
The Example Pit shows explicit declaration of the _start_ and _stop_ actions.
The _start_ and _stop_ declarations cause them to be called every iteration, as seen in the output listing.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="Ping">
    <String value="PING" token="true"/>
  </DataModel>

  <StateModel name="TheStateModel" initialState="InitialState">
    <State name="InitialState">

      <!-- This action is called on every iteration. It will cause
           the Tcp Publisher to perform any initialization. -->
      <Action type="start" />

      <!-- This action is called on every iteration. It will cause the
           Tcp Publisher to open a connection to the remote host. -->
      <Action type="open" />

      <!-- This action is called on every iteration. It will output data from
           the data model "Ping" using our Publisher. -->
      <Action type="output">
        <DataModel ref="Ping"/>
      </Action>

      <!-- This action is called on every iteration. It will cause the
           Tcp Publisher to close its connection to the remote host if it's
           still open. -->
      <Action type="close" />

      <!-- This action is called on every iteration. It will perform any
           final clean up actions to fully stop the Publisher. -->
      <Action type="stop" />

    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheStateModel"/>
    <Publisher class="Tcp">
      <Param name="Host" value="127.0.0.1" />
      <Param name="Port" value="31337" />
    </Publisher>

    <Logger class="File" >
      <Param name="Path" value="logs"/>
    </Logger>
  </Test>
</Peach>
----

In the following output, the _start_ action executes at the beginning of every iteration and the _stop_ action follows at the end of every iteration.

----
> peach --range 1,3 --seed 51405 example.xml

[[ Peach Professional v3.0.0
[[ Copyright (c) Peach Fuzzer LLC
Peach.Core.Engine runTest: context.config.range == true, start: 1, stop: 3

[*] Test 'Default' starting with random seed 51405.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Start
Peach.Core.Publishers.TcpClientPublisher start()                             <1>
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Open
Peach.Core.Publishers.TcpClientPublisher open()
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.TcpClientPublisher output(4 bytes)
Peach.Core.Publishers.TcpClientPublisher

00000000   50 49 4E 47                                        PING

Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Close
Peach.Core.Publishers.TcpClientPublisher close()
Peach.Core.Publishers.TcpClientPublisher Shutting down connection to 127.0.0.1:31337
Peach.Core.Publishers.TcpClientPublisher Read 0 bytes from 127.0.0.1:31337, closing client connection.
Peach.Core.Publishers.TcpClientPublisher Closing connection to 127.0.0.1:31337
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Stop
Peach.Core.Publishers.TcpClientPublisher stop()                              <2>

[1,3,0:00:04.512] Performing iteration
Peach.Core.Dom.Action ActionType.Start
Peach.Core.Publishers.TcpClientPublisher start()                             <3>
Peach.Core.Dom.Action ActionType.Open
Peach.Core.Publishers.TcpClientPublisher open()
[*] Fuzzing: Ping.DataElement_0
[*] Mutator: DataElementSwapNearNodesMutator
Peach.Core.MutationStrategies.RandomStrategy Action_Starting: Fuzzing: Ping.DataElement_0
Peach.Core.MutationStrategies.RandomStrategy Action_Starting: Mutator: DataElementSwapNearNodesMutator
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.TcpClientPublisher output(4 bytes)
Peach.Core.Publishers.TcpClientPublisher

00000000   50 49 4E 47                                        PING

Peach.Core.Dom.Action ActionType.Close
Peach.Core.Publishers.TcpClientPublisher close()
Peach.Core.Publishers.TcpClientPublisher Shutting down connection to 127.0.0.1:31337
Peach.Core.Publishers.TcpClientPublisher Read 0 bytes from 127.0.0.1:31337, closing client connection.
Peach.Core.Publishers.TcpClientPublisher Closing connection to 127.0.0.1:31337
Peach.Core.Dom.Action ActionType.Stop
Peach.Core.Publishers.TcpClientPublisher stop()                              <4>

[2,3,0:00:05.246] Performing iteration
Peach.Core.Dom.Action ActionType.Start
Peach.Core.Publishers.TcpClientPublisher start()                             <5>
Peach.Core.Dom.Action ActionType.Open
Peach.Core.Publishers.TcpClientPublisher open()
[*] Fuzzing: Ping.DataElement_0
[*] Mutator: UnicodeUtf8ThreeCharMutator
Peach.Core.MutationStrategies.RandomStrategy Action_Starting: Fuzzing: Ping.DataElement_0
Peach.Core.MutationStrategies.RandomStrategy Action_Starting: Mutator: UnicodeUtf8ThreeCharMutator
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.TcpClientPublisher output(522 bytes)
Peach.Core.Publishers.TcpClientPublisher

00000000   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000010   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000020   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
00000030   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000040   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000050   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
00000060   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000070   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000080   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
00000090   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
000000A0   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
000000B0   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
000000C0   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
000000D0   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
000000E0   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
000000F0   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000100   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000110   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
00000120   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000130   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000140   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
00000150   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000160   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000170   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
00000180   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000190   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
000001A0   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
000001B0   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
000001C0   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
000001D0   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
000001E0   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
000001F0   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000200   B0 EF 83 B0 EF 83 B0 EF  83 B0                     ..........

Peach.Core.Dom.Action ActionType.Close
Peach.Core.Publishers.TcpClientPublisher close()
Peach.Core.Publishers.TcpClientPublisher Shutting down connection to 127.0.0.1:31337
Peach.Core.Publishers.TcpClientPublisher Read 0 bytes from 127.0.0.1:31337, closing client connection.
Peach.Core.Publishers.TcpClientPublisher Closing connection to 127.0.0.1:31337
Peach.Core.Dom.Action ActionType.Stop
Peach.Core.Publishers.TcpClientPublisher stop()                              <6>

[3,3,0:00:01.705] Performing iteration
Peach.Core.Dom.Action ActionType.Start
Peach.Core.Publishers.TcpClientPublisher start()                             <7>
Peach.Core.Dom.Action ActionType.Open
Peach.Core.Publishers.TcpClientPublisher open()
[*] Fuzzing: Ping.DataElement_0
[*] Mutator: UnicodeUtf8ThreeCharMutator
Peach.Core.MutationStrategies.RandomStrategy Action_Starting: Fuzzing: Ping.DataElement_0
Peach.Core.MutationStrategies.RandomStrategy Action_Starting: Mutator: UnicodeUtf8ThreeCharMutator
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.TcpClientPublisher output(1968 bytes)
Peach.Core.Publishers.TcpClientPublisher


00000000   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000010   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000020   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
00000030   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000040   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000050   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
00000060   EF 83 B0 EF 83 B0 EF 83  B0 EF 83 B0 EF 83 B0 EF   ................
00000070   83 B0 EF 83 B0 EF 83 B0  EF 83 B0 EF 83 B0 EF 83   ................
00000080   B0 EF 83 B0 EF 83 B0 EF  83 B0 EF 83 B0 EF 83 B0   ................
....



Peach.Core.Dom.Action ActionType.Close
Peach.Core.Publishers.TcpClientPublisher close()
Peach.Core.Publishers.TcpClientPublisher Shutting down connection to 127.0.0.1:31337
Peach.Core.Publishers.TcpClientPublisher Read 0 bytes from 127.0.0.1:31337, closing client connection.
Peach.Core.Publishers.TcpClientPublisher Closing connection to 127.0.0.1:31337
Peach.Core.Dom.Action ActionType.Stop
Peach.Core.Publishers.TcpClientPublisher stop()                              <8>
----
<1> _Start_ action at beginning of iteration
<2> _Stop_ action at end of iteration
<3> _Start_ action at beginning of iteration
<4> _Stop_ action at end of iteration
<5> _Start_ action at beginning of iteration
<6> _Stop_ action at end of iteration
<7> _Start_ action at beginning of iteration
<8> _Stop_ action at end of iteration

==========================
