[[JumpStart]]
== Getting Started with the Peach Fuzzer Platform

This section provides a workflow that identifies the steps involved in setting up and running a fuzzing session. 
Stepping through the Peach fuzzing workflow is the quickest way to begin fuzzing.

The workflow in this section is conceptual. 
It tells you what needs to be done; 
not how to do it. 
Yet, 
when we can, 
we refer to the appropriate section of the Peach User Guide to perform that part of the workflow.

[NOTE]
=======
If you're new to fuzzing or want to learn how fuzzing works, 
read the section xref:Intro_to_FuzzingBrand_new_items[Introduction to Fuzzing].

This approach applies to any step of the workflow that you are unfamiliar with or that you are curious about. 
Read the section. 
Then, come back to the workflow for the next task.
=======

The workflow includes the following steps. The first item in the workflow is your test target. 
You should have this item locked down, 
as it makes the other steps of the workflow easier to get through.

. xref:WF1_PickTarget[Picking Your Fuzzing Target]
. xref:WF2_InstallPeach[Installing Peach]
. xref:WF3_LaunchPeach[Launching Peach]
. xref:WF4_SelectPit[Selecting a Peach Pit (fuzzing definition for your test target)]
. xref:WF5_SpecifyTestConfiguration[Specifying a Test Configuration]
. xref:WF6_RunFuzzJob[Running the Fuzzing Job]
. xref:WF7_InterpretResults[Interpreting Results]
. xref:WF8_FixIssuesAndRerun[Fixing Issues and Re-running the Faulting Test Cases]

The following is a restatement of the workflow that includes descriptions and appropriate references. 
After you've been through the workflow once or twice, you shouldn't need to access the details again.

[[WF1_PickTarget]]
=== Picking your fuzzing target

A fuzzing target can be just about anything; 
typically, 
the target accepts and dispenses data through security boundaries. 
Fuzzing target examples include:

* An application that consumes files
* A protocol service
* A protocol client
* A device
* Other

Get a good idea of what you intend to fuzz.

[[WF2_InstallPeach]]
=== Installing Peach

The xref:Installation[Installation] section includes instructions for installing Peach Fuzzer on Windows, 
three Linux distributions, 
and OS X. 
The scope of material includes downloading distribution images with your Peach license through 
launching the platform to ensure a correct installation.

The installation also identifies other applications that Peach uses and where needed, 
provides installation on these items.

A video of the installation titled 
https://vimeo.com/148176046[Installing Your Peach Fuzzer Professional or Enterprise Software] 
is available at http://www.vimeo.com[vimeo.com].

[[WF3_LaunchPeach]]
=== Launching Peach

The xref:Start_Peach_Web[Starting the {peachweb}] section describes how to launch Peach and the Peach Web UI.

[NOTE]
=======
. A command processor or command shell at a heightened/administrative level is used to launch Peach.
. In the Windows environment, Peach automatically starts a browser and loads the Web UI.
+
For other environments, 
you need to copy the URL generated by Peach, 
launch a browser, 
and connect to Peach by pasting the URL into the browser address bar.
=======

[[WF4_SelectPit]]
=== Selecting a Peach Pit

From the Peach Web Home page, 
click the “Library” icon in the group of icons on the left side of the page that are above the menu entries. 
This action lets you start with a pit installed on your system.

If you need a Pit that is not in your library, 
please contact the Peach Fuzzer Sales team at sales@peachfuzzer.com. 
For a list of available Pits, 
visit the http://peachfuzzer.com[Peach Fuzzer] web site. 
From the Peach Fuzzer homepage, 
click on  "Products" in the banner at the top of the page, 
then click the "Peach Pits" menu entry.

[[WF5_SpecifyTestConfiguration]]
=== Specifying a Test Configuration

Specifying a configuration consists of setting variables specific to the selected Pit and defining how to monitor the test subject.

Variables are used to configure and target a Pit. 
This includes information such as IP addresses and port numbers for network Pits and any configuration required a specific Pit. 
Many of the variables you already know or can obtain quickly. 
Sometimes, 
the value of a variable depends on the monitoring setup, 
so some tweaking might be appropriate once you select the monitors to use.

Several monitoring recipes are included to provide base monitor configurations for the different fuzzing targets. 
Monitors focus on detecting faults, 
collecting data, 
and automating the test environment. 
The monitoring recipes also are great starting points for developing your own configurations that precisely monitor the test target for your needs. 
The recipes in this release consist of the following:

* xref:Recipe_FileFuzzing[Monitoring a File Consumer (File Fomat)]
* xref:Recipe_LinuxNetServer[Monitoring a Linux Network Service]
* xref:Recipe_LinuxNetClient[Monitoring a Linux Network Client]
* xref:Recipe_NetDevice[Monitoring a Network Device]
* xref:Recipe_WindowsNetServer[Monitoring a Windows Network Service]
* xref:Recipe_WindowsNetClient[Monitoring a Windows Network Client]

[[WF6_RunFuzzJob]]
=== Running the Fuzzing Job

Peach Fuzzer typically runs hundreds of thousands of test cases. 
The Peach Fuzzer engine will generate an unlimited number of test cases, 
though this is not typically the most efficient use of resources. 
For more information, see xref:Fuzzing_ExitCriteria[When to Stop Fuzzing]. 
In each fuzzing job, 
Peach generates test cases randomly with fresh data values. 
The Peach platform weights the mutations used to generate the most faults.

Once your configuration is complete, 
or if you selected an existing configuration, 
you can start a fuzzing job by clicking Start at the bottom of the configuration page. 
For more information on starting and re-running fuzzing jobs, 
see the xref:Start_Fuzzing[Fuzzing Session] section for more information.

NOTE: A fuzzing job runs indefinitely. 
It will stop running if you specify a value for Stop Test Case or if you manually click Stop on the Peach dashboard.

[[WF7_InterpretResults]]
=== Interpreting Results

When the fuzzing job completes, Peach provides two sets of results:

* A report of the fuzzing job in a `.pdf` file.
* Online information that buckets the results, and provides drill-down capability

The report provides an overall status of the job and provides many views of the fuzzing job by focusing on the metrics used in fuzzing. 
The report is available by locating the appropriate fuzzing job entry, 
then clicking on the document in the Action column at the right side of the entry.

Review the overall metrics and the buckets/categories of faults that occur. 
You should be able to see what worked well and where the issues were. 
After that, 
you'll need to investigate the faults, 
find the root cause of the fault, 
and then deal with it accordingly.

The online results focus on the faults that occurred during the fuzzing job. 
The faults are where you need to focus, 
and where Peach Fuzzer adds value to the SDL. 
You can access faults from the Dashboard page or from the home page, 
where you can access all of the stored fuzzing job results.

See the xref:Report_Faults[Faults] section for a description of the information that Peach captures when a fault occurs; 
visit the xref:Report_Metrics[Metrics] section for a description of how Peach Fuzzer provides meaningful views into the fuzzing job by rolling up test case results.

[[WF8_FixIssuesAndRerun]]
=== Fixing Issues and Re-running Test Cases

The last step is to address the faults/issues uncovered during fuzzing, and to verify the fixes.

* Address the faults +
This item is for the developer, who needs to edit the code where the fault occurred. 
Use your normal debugging practices here.

* Verifying fixes of issues +
When the fixes are in place, 
you can re-run a fuzzing job in whole or in part by selecting the Pit Configuration, 
and then specifying the Seed value of the fuzzing job that you found the fault, 
the Start Test Case (optional), 
and the End Test Case (optional). 
For more information, 
see xref:Re-Fuzzing[Re-running a Fuzzing Job].

TIP: Specifying the same the seed value as in the original fuzzing job ensures that the same test cases are run, 
in the same sequence and with the same data as in the original fuzzing job.

// end
