
[[Analyzers_Json]]
== JSON Analyzer

This analyzer converts JSON strings into a full data model. 

When used in the DataModel section of a Peach Pit, the Fuzzer walks the JSON data and creates the appropriate elements. 

When used from the command line, the Fuzzer walks the JSON data, creates the appropriate elements, and saves the results of the generated model to disk. Once saved, you can use and modify the results as needed. 

IMPORTANT: The JSON analyzer requires data from a String data type. 

=== Syntax

[source,xml]
----
<String name="JsonData">
	<Analyzer class="Json" />
</String>
----

----
pittool analyzer Json input.txt output.xml
----

=== Command Line Syntax

----
pittool analyzer Json <input file> <output file>
----

input file::
    File containing JSON encoded data.

output file::
    File creating containing generated data model

=== Attributes

_Required:_

There are no required attributes.

_Optional:_

There are no optional attributes.

=== Examples

.JSON Inline Example
==========================
This example uses the JSON analyzer on inline data. 

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

	<DataModel name="TheModel">
		<String value='{"Foo":["Bar",1,null],"Null":null,"Bool":false,"Obj":{"Num":1,"Str":"StringValue"},"Double":1.2}'>
			<Analyzer class="Json" />
		</String>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<Action type="output">
				<DataModel ref="TheModel" />
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>
		<Publisher class="ConsoleHex" />
	</Test>
</Peach>
----

Output from inline example.
----
> peach -1 --debug example.xml

[*] Test 'Default' starting with random seed 56481.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.StateModel Run(): Changing to state "initial".
Peach.Core.Dom.Action Run(Action): Output
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(96 bytes)
00000000   7B 22 46 6F 6F 22 3A 5B  22 42 61 72 22 2C 31 2C   {"Foo":["Bar",1,
00000010   6E 75 6C 6C 5D 2C 22 4E  75 6C 6C 22 3A 6E 75 6C   null],"Null":nul
00000020   6C 2C 22 42 6F 6F 6C 22  3A 66 61 6C 73 65 2C 22   l,"Bool":false,"
00000030   4F 62 6A 22 3A 7B 22 4E  75 6D 22 3A 31 2C 22 53   Obj":{"Num":1,"S
00000040   74 72 22 3A 22 53 74 72  69 6E 67 56 61 6C 75 65   tr":"StringValue
00000050   22 7D 2C 22 44 6F 75 62  6C 65 22 3A 31 2E 32 7D   "},"Double":1.2}
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----

.JSON Data From File Example
==========================
This example uses the JSON analyzer on an external file containing JSON encoded data. 

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

	<DataModel name="TheModel">
		<String>  
			<Analyzer class="Json" />
		</String>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<Action type="output">
				<DataModel ref="TheModel" />
				<Data name="Json" fileName="json.json"/> 
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>
		<Publisher class="ConsoleHex" />
	</Test>
</Peach>
----

Output from JSON data file example.
----
> peach -1 --debug example.xml

[*] Test 'Default' starting with random seed 33175.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Cracker.DataCracker ------------------------------------
Peach.Core.Cracker.DataCracker DataModel 'TheModel' Bytes: 0/96, Bits: 0/768
Peach.Core.Cracker.DataCracker getSize: -----> DataModel 'TheModel'
Peach.Core.Cracker.DataCracker scan: DataModel 'TheModel'
Peach.Core.Cracker.DataCracker scan: String 'TheModel.DataElement_0' -> Offset: 0, Unsized element
Peach.Core.Cracker.DataCracker getSize: <----- Deterministic: ???
Peach.Core.Cracker.DataCracker Crack: DataModel 'TheModel' Size: <null>, Bytes: 0/96, Bits: 0/768
Peach.Core.Cracker.DataCracker ------------------------------------
Peach.Core.Cracker.DataCracker String 'TheModel.DataElement_0' Bytes: 0/96, Bits: 0/768
Peach.Core.Cracker.DataCracker getSize: -----> String 'TheModel.DataElement_0'
Peach.Core.Cracker.DataCracker scan: String 'TheModel.DataElement_0' -> Offset: 0, Unsized element
Peach.Core.Cracker.DataCracker lookahead: String 'TheModel.DataElement_0'
Peach.Core.Cracker.DataCracker getSize: <----- Last Unsized: 768
Peach.Core.Cracker.DataCracker Crack: String 'TheModel.DataElement_0' Size: 768, Bytes: 0/96, Bits: 0/768
Peach.Core.Dom.DataElement String 'TheModel.DataElement_0' value is: {"Foo":["Bar",1,null],"Null":null,"Bool":false,"Obj":{"Num":1,"S.. (Len: 96 chars)
Peach.Core.Dom.StateModel Run(): Changing to state "initial".
Peach.Core.Dom.Action Run(Action): Output
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(96 bytes)
00000000   7B 22 46 6F 6F 22 3A 5B  22 42 61 72 22 2C 31 2C   {"Foo":["Bar",1,
00000010   6E 75 6C 6C 5D 2C 22 4E  75 6C 6C 22 3A 6E 75 6C   null],"Null":nul
00000020   6C 2C 22 42 6F 6F 6C 22  3A 66 61 6C 73 65 2C 22   l,"Bool":false,"
00000030   4F 62 6A 22 3A 7B 22 4E  75 6D 22 3A 31 2C 22 53   Obj":{"Num":1,"S
00000040   74 72 22 3A 22 53 74 72  69 6E 67 56 61 6C 75 65   tr":"StringValue
00000050   22 7D 2C 22 44 6F 75 62  6C 65 22 3A 31 2E 32 7D   "},"Double":1.2}
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----