[[TutorialFileFuzzing_ConfigurePublisher]]

== Configure Publisher

The last thing we need to do before we can try out our nifty fuzzer is to configure a xref:Publisher[Publisher].
xref:Publisher[Publisher]s are I_O connectors that implement the plumbing between actions like _output_, _input_, and _call_.
For our file fuzzer, we will use the xref:Publisher[Publisher] called xref:Publishers_File[File].
This publisher allows us to write out a file and then launch a process using the _call_ action like we setup in last section.

Configuring our publisher is easy, just locate the following XML near the bottom of the +wav.xml+ file,
it is a child of xref:Test[Test].

[source,xml]
----
<!-- TODO: Complete publisher -->
<Publisher />
----


Now, this publisher takes a single parameter called _FileName_ that contains the file name of the fuzzed file.
This should be the same as the file name we specified in the _call_ action (+fuzzed.wav+).

[source,xml]
----
<Publisher class="File">
    <Param name="FileName" value="fuzzed.wav"/>
</Publisher>
----

=== What's Next?

Now we need a way to detect when our target crashes and also run our target.
We will also want to collect some information like a stack trace to look at later on.
Head to the next section to learn how to configure an agent and monitor.

// end
