<<<
[[Transformers_Bz2CompressTransformer]]
== Bz2Compress

// Reviewed:
//  - 02/19/2014: Seth & Adam: Outlined
// TODO:
// Verify parameters expand parameter description
// Full pit example using hex console
// expand  general description
// Identify direction / actions supported for (Input/Output/Call/setProperty/getProperty)
// See AES for format
// Test output, input

// Updated:
// 2/20/14: Mick
// verified params
// added supported actions
// expanded description
// added full example

[horizontal]
Type:: Compress

_Bz2Compress_ performs a bzip2 compression on the value in the parent xref:DataModel[DataModel].

The xref:Transformer[Transformer] can bidirectionally compress data as well as decompress data.

=== Parameters

None.

=== Attributes

_Required:_

None.

_Optional:_

None.

=== Actions Supported

xref:Action_input[input]:: On input, this transformer decompresses the incoming data.
xref:Action_output[output]:: On output, this transformer compresses the outgoing data.

=== Examples

.Compression To and From File Example
==========================
This example uses Bz2Compress to compress a value, write the value to the console, write to a file, and then read it from the file.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="Ex1">
    <String name="TransformMe" value="shrinkmepleaseshrinkmeplease">
      <Transformer class="Bz2Compress" />
    </String>
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <!-- Compressed Output -->
      <Action type="output" publisher="ConsolePub">
        <DataModel ref="Ex1" />
      </Action>

      <!-- Write Compressed Output to File -->
      <Action type="output" publisher="FilePubWrite">
        <DataModel ref="Ex1" />
        <Data>
          <Field name="TransformMe" value="shrinkmepleaseshrinkmeplease" />
        </Data>
      </Action>

      <Action type="close" publisher="FilePubWrite" />
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>

    <Publisher class="ConsoleHex" name="ConsolePub"/>

    <Publisher class="File" name="FilePubWrite">
      <Param name="FileName" value="compressed.bin" />
    </Publisher>
  </Test>
</Peach>
----

Output from this example.
----
> peach -1 --debug example.xml

[*] Test 'Default' starting with random seed 47050.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(53 bytes)
00000000   42 5A 68 39 31 41 59 26  53 59 A7 83 53 78 00 00   BZh91AY&SY??Sx??
00000010   0D 81 80 22 6F 58 00 20  00 31 00 D3 4D 01 55 03   ???"oX? ?1??M?U?
00000020   41 EA 5D 4D A1 1E 44 47  51 18 7C 5D C9 14 E1 42   A?]M??DGQ?|]???B
00000030   42 9E 0D 4D E0                                     B??M?
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.FilePublisher start()
Peach.Core.Publishers.FilePublisher open()
Peach.Core.Publishers.FilePublisher output(53 bytes)
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Close
Peach.Core.Publishers.FilePublisher close()
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()
Peach.Core.Publishers.FilePublisher stop()

[*] Test 'Default' finished.
----
==========================
