<<<
[[Transformers_HexTransformer]]
== Hex

// Reviewed:
//  - 02/19/2014: Seth & Adam: Outlined
// TODO:
// Verify parameters expand parameter description
// Full pit example using hex console
// expand general description
// Identify direction / actions supported for (Input/Output/Call/setProperty/getProperty)
// See AES for format
// Test output, input

// Updated:
// 2/19/14: Mick
// verified params
// added supported actions
// expanded description
// added full example

[horizontal]
Type:: Encoder/Decoder

_HexTransformer_ takes the provided value and produces an ASCII string of hex characters that represent the data.

The xref:Transformer[Transformer] can bidirectionally transform this data from hex to string.

=== Parameters

None.

=== Attributes

None.

=== Actions Supported

xref:Action_input[input]:: On input, HexTransformer converts a hex string into ASCII for the incoming data.
xref:Action_output[output]:: On output, HexTransformer converts ASCII into a hex string for the outgoing data.

=== Examples

.Simple Console Example
==========================


[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

	<DataModel name="Ex1">
		<String name="TransformMe" value="ABCDEF">
			<Transformer class="Hex" />
		</String>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<!-- Encoded Output -->
			<Action type="output" publisher="ConsolePub">
				<DataModel ref="Ex1" />
			</Action>

			<!-- Write Encoded Output to File -->
			<Action type="output" publisher="FilePubWrite">
				<DataModel ref="Ex1" />
				<Data>
					<Field name="TransformMe" value="ABCDEF" />
				</Data>
			</Action>

			<Action type="close" publisher="FilePubWrite" />

			<!-- Read and decode encoded file and slurp decoded string to output in console -->
			<Action type="input" publisher="FilePubRead" >
				<DataModel name="InputModel" ref="Ex1" />
			</Action>

			<Action type="slurp" valueXpath="//InputModel//TransformMe" setXpath="//OutputModel//StringValue" />

			<Action type="output" publisher="ConsolePub">
				<DataModel name="OutputModel">
					<String name="StringValue" />
				</DataModel>
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex" name="ConsolePub"/>

		<Publisher class="File" name="FilePubWrite">
			<Param name="FileName" value="encoded.bin" />
		</Publisher>

		<Publisher class="File" name="FilePubRead">
			<Param name="FileName" value="encoded.bin" />
			<Param name="Overwrite" value="false" />
		</Publisher>
	</Test>
</Peach>
----

Output from this example.
----
> peach -1 --debug example.xml


[*] Test 'Default' starting with random seed 47130.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(12 bytes)
00000000   34 31 34 32 34 33 34 34  34 35 34 36               414243444546
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.FilePublisher start()
Peach.Core.Publishers.FilePublisher open()
Peach.Core.Publishers.FilePublisher output(12 bytes)
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Close
Peach.Core.Publishers.FilePublisher close()
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Input
Peach.Core.Publishers.FilePublisher start()
Peach.Core.Publishers.FilePublisher open()
Peach.Core.Publishers.FilePublisher input()
Peach.Core.Cracker.DataCracker ------------------------------------
Peach.Core.Cracker.DataCracker DataModel 'InputModel' Bytes: 0/12, Bits: 0/96
Peach.Core.Cracker.DataCracker getSize: -----> DataModel 'InputModel'
Peach.Core.Cracker.DataCracker scan: DataModel 'InputModel'
Peach.Core.Cracker.DataCracker scan: String 'InputModel.TransformMe' -> Offset: 0, Unsized element
Peach.Core.Cracker.DataCracker getSize: <----- Deterministic: ???
Peach.Core.Cracker.DataCracker Crack: DataModel 'InputModel' Size: <null>, Bytes : 0/12, Bits: 0/96
Peach.Core.Cracker.DataCracker ------------------------------------
Peach.Core.Cracker.DataCracker String 'InputModel.TransformMe' Bytes: 0/12, Bits : 0/96
Peach.Core.Cracker.DataCracker getSize: -----> String 'InputModel.TransformMe'
Peach.Core.Cracker.DataCracker scan: String 'InputModel.TransformMe' -> Offset: 0, Unsized element
Peach.Core.Cracker.DataCracker lookahead: String 'InputModel.TransformMe'
Peach.Core.Cracker.DataCracker getSize: <----- Last Unsized: 96
Peach.Core.Cracker.DataCracker Crack: String 'InputModel.TransformMe' Size: 48, Bytes: 0/6, Bits: 0/48
Peach.Core.Dom.DataElement String 'InputModel.TransformMe' value is: ABCDEF
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Slurp
Peach.Core.Dom.Action Slurp, setting OutputModel.StringValue from InputModel.TransformMe
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher output(6 bytes)
00000000   41 42 43 44 45 46                                  ABCDEF
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Publishers.FilePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()
Peach.Core.Publishers.FilePublisher stop()
Peach.Core.Publishers.FilePublisher stop()

[*] Test 'Default' finished.
----
==========================