<<<
[[Transformers_JsEncodeTransformer]]
== JsEncode

// Reviewed:
//  - 02/19/2014: Seth & Adam: Outlined
// TODO:
// Verify parameters expand parameter description
// Full pit example using hex console
// expand  general description
// Identify direction / actions supported for (Input/Output/Call/setProperty/getProperty)
// See AES for format
// Test output, input

// Updated:
// 2/19/14: Mick
// verified params
// added supported actions
// expanded description
// added full example

[horizontal]
Type:: Encoder/Decoder

_JsEncode_ produces a JavaScript-encoded result of the value in the parent xref:DataModel[DataModel].
All characters are encoded.

This xref:Transformer[Transformer] only encodes the output. _JsEncode_ does not decode any input.

The _JsEncode_ algorithm filters alphabetic characters (A-Z, a-z), numerals (0-9), spaces, commas, and periods to pass through the transformer unaltered. Other characters are filtered and have formatting applied to them. 

=== Parameters

None.

=== Attributes

None.

=== Actions Supported

xref:Action_output[output]:: On output, this transformer encodes the value using the _JsEncode_ algorithm to the outgoing data.

=== Examples

.Simple Encode Example
==========================
This example uses _JsEncode_ on an inline value and writes the transformed value to the console.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

	<DataModel name="Ex1">
		<String value="JSEncoded: " token="true"/>
		<String name="TransformMe" value="~!@#$%^&amp;*()_+-=`?.,">
			<Transformer class="JsEncode" />
		</String>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<!-- Encoded XML Output -->
			<Action type="output" publisher="ConsolePub">
				<DataModel ref="Ex1" />
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex" name="ConsolePub"/>
	</Test>
</Peach>
----

Output from this example.
----
> peach -1 --debug example.xml

[*] Test 'Default' starting with random seed 33041.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(81 bytes)
00000000   4A 53 45 6E 63 6F 64 65  64 3A 20 5C 78 37 45 5C   JSEncoded: \x7E\
00000010   78 32 31 5C 78 34 30 5C  78 32 33 5C 78 32 34 5C   x21\x40\x23\x24\
00000020   78 32 35 5C 78 35 45 5C  78 32 36 5C 78 32 41 5C   x25\x5E\x26\x2A\
00000030   78 32 38 5C 78 32 39 5C  78 35 46 5C 78 32 42 5C   x28\x29\x5F\x2B\
00000040   78 32 44 5C 78 33 44 5C  78 36 30 5C 78 33 46 2E   x2D\x3D\x60\x3F.
00000050   2C                                                 ,
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
==========================