<<<
[[Transformers_NetBiosDecodeTransformer]]
== NetBiosDecode

// Reviewed:
//  - 02/19/2014: Seth & Adam: Outlined
// TODO:
// Verify parameters expand parameter description
// Full pit example using hex console
// expand  general description
// Identify direction / actions supported for (Input/Output/Call/setProperty/getProperty)
// See AES for format
// Test output, input

// Updated:
// 2/19/14: Mick
// verified params
// added supported actions
// expanded description
// added full example

[horizontal]
Type:: Encoder/Decoder

_NetBiosDecode_ decodes NetBios-encoded strings.

The xref:Transformer[Transformer] can bidirectionally encode data as well as decode data.

=== Parameters

_Required:_

None.

_Optional:_

pad:: Boolean value that determines whether the NetBios name should be padded/trimmed to 32 bytes.

=== Attributes

None.

=== Actions Supported

xref:Action_input[input]:: On input, this transformer encodes incoming data using the NetBios encoding algorithm.
xref:Action_output[output]:: On output, this transformer decodes outgoing data using the NetBios decoding algorithm.

=== Examples

.Decoding Value To and From File Example
==========================
This example uses NetBiosDecode on an inline value, writes the transformed value to a file, and reads the value from the file to the console.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

	<DataModel name="Ex1">
		<String value="NetBiosDecoded: " token="true"/>
		<String name="TransformMe" value="45 4D 45 42 45 4F 45 4E 45 42 45 4F" valueType="hex">
			<Transformer class="NetBiosDecode" />
		</String>
	</DataModel>


	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<!-- Decoded Output -->
			<Action type="output" publisher="ConsolePub">
				<DataModel ref="Ex1" />
			</Action>

			<!-- Write Encoded Output to File -->
			<Action type="output" publisher="FilePubWrite">
				<DataModel ref="Ex1" />
				<Data>
					<Field name="TransformMe" value="45 4D 45 42 45 4F 45 4E 45 42 45 4F" valueType="hex"/>
				</Data>
			</Action>
			<Action type="close" publisher="FilePubWrite" />

			<!-- Read and decode encoded file and slurp the XML body to output in console -->
			<Action type="input" publisher="FilePubRead" >
				<DataModel name="InputModel" ref="Ex1" />
			</Action>
			<Action type="slurp" valueXpath="//InputModel//TransformMe" setXpath="//OutputModel//StringValue" />
			<Action type="output" publisher="ConsolePub">
				<DataModel name="OutputModel">
					<String name="StringValue" />
				</DataModel>
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex" name="ConsolePub"/>

		<Publisher class="File" name="FilePubWrite">
			<Param name="FileName" value="encrypted.bin" />
		</Publisher>

		<Publisher class="File" name="FilePubRead">
			<Param name="FileName" value="encrypted.bin" />
			<Param name="Overwrite" value="false" />
		</Publisher>
	</Test>
</Peach>
----

Output from this example.
----
> peach -1 --debug example.xml

[*] Test 'Default' starting with random seed 54340.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(22 bytes)
00000000   4E 65 74 42 69 6F 73 44  65 63 6F 64 65 64 3A 20   NetBiosDecoded:
00000010   4C 41 4E 4D 41 4E                                  LANMAN
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.FilePublisher start()
Peach.Core.Publishers.FilePublisher open()
Peach.Core.Publishers.FilePublisher output(22 bytes)
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Close
Peach.Core.Publishers.FilePublisher close()
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Input
Peach.Core.Publishers.FilePublisher start()
Peach.Core.Publishers.FilePublisher open()
Peach.Core.Publishers.FilePublisher input()
Peach.Core.Cracker.DataCracker ------------------------------------
Peach.Core.Cracker.DataCracker DataModel 'InputModel' Bytes: 0/22, Bits: 0/176
Peach.Core.Cracker.DataCracker getSize: -----> DataModel 'InputModel'
Peach.Core.Cracker.DataCracker scan: DataModel 'InputModel'
Peach.Core.Cracker.DataCracker scan: String 'InputModel.DataElement_0' -> Pos: 0, Saving Token
Peach.Core.Cracker.DataCracker scan: String 'InputModel.DataElement_0' -> Pos: 128, Length: 128
Peach.Core.Cracker.DataCracker getSize: <----- Deterministic: ???
Peach.Core.Cracker.DataCracker Crack: DataModel 'InputModel' Size: <null>, Bytes
: 0/22, Bits: 0/176
Peach.Core.Cracker.DataCracker ------------------------------------
Peach.Core.Cracker.DataCracker String 'InputModel.DataElement_0' Bytes: 0/22, Bits: 0/176
Peach.Core.Cracker.DataCracker getSize: -----> String 'InputModel.DataElement_0'

Peach.Core.Cracker.DataCracker scan: String 'InputModel.DataElement_0' -> Pos: 0, Saving Token
Peach.Core.Cracker.DataCracker scan: String 'InputModel.DataElement_0' -> Pos: 128, Length: 128
Peach.Core.Cracker.DataCracker getSize: <----- Size: 128
Peach.Core.Cracker.DataCracker Crack: String 'InputModel.DataElement_0' Size: 128, Bytes: 0/22, Bits: 0/176
Peach.Core.Dom.DataElement String 'InputModel.DataElement_0' value is: NetBiosDecoded:
Peach.Core.Cracker.DataCracker ------------------------------------
Peach.Core.Cracker.DataCracker String 'InputModel.TransformMe' Bytes: 16/22, Bit s: 128/176
Peach.Core.Cracker.DataCracker getSize: -----> String 'InputModel.TransformMe'
Peach.Core.Cracker.DataCracker scan: String 'InputModel.TransformMe' -> Offset: 0, Unsized element
Peach.Core.Cracker.DataCracker lookahead: String 'InputModel.TransformMe'
Peach.Core.Cracker.DataCracker getSize: <----- Last Unsized: 48
Peach.Core.Cracker.DataCracker Crack: String 'InputModel.TransformMe' Size: 96, Bytes: 0/12, Bits: 0/96
Peach.Core.Dom.DataElement String 'InputModel.TransformMe' value is: EMEBEOENEBEO
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Slurp
Peach.Core.Dom.Action Slurp, setting OutputModel.StringValue from InputModel.TransformMe
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher output(12 bytes)
00000000   45 4D 45 42 45 4F 45 4E  45 42 45 4F               EMEBEOENEBEO
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Publishers.FilePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()
Peach.Core.Publishers.FilePublisher stop()
Peach.Core.Publishers.FilePublisher stop()

[*] Test 'Default' finished.
----
==========================