<<<
[[Transformers_UrlEncodeTransformer]]
== UrlEncode

// Reviewed:
//  - 02/19/2014: Seth & Adam: Outlined
// TODO:
// Verify parameters expand parameter description
// Full pit example using hex console
// expand  general description
// Identify direction / actions supported for (Input/Output/Call/setProperty/getProperty)
// See AES for format
// Test output, input

// Updated:
// 2/19/14: Mick
// verified params
// added supported actions
// expanded description
// added full example

[horizontal]
Type:: Encoder/Decoder

_UrlEncode_ produces a URL-encoded string of the provided value in the parent xref:DataModel[DataModel].

The xref:Transformer[Transformer] can bidirectionally encode data as well as decode data.

=== Parameters

None.

=== Attributes

None.

=== Actions Supported

xref:Action_input[input]:: On input, this transformer decodes a URL-encoded string.
xref:Action_output[output]:: On output, this transformer encodes a URL-encoded string.

=== Examples

.Simple Encode Example
==========================
This example uses UrlEncode on an inline value, writes the transformed value to a file, and reads the value from the file to the console.


[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

	<DataModel name="Ex1">
		<String value="http://peachfuzzer.com/?q=" token="true"/>
		<String name="TransformMe" value="'abcd=1234'">
			<Transformer class="UrlEncode" />
		</String>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<!-- Encoded URL Output -->
			<Action type="output" publisher="ConsolePub">
				<DataModel ref="Ex1" />
			</Action>

			<!-- Write Encoded Output to File -->
			<Action type="output" publisher="FilePubWrite">
				<DataModel ref="Ex1" />
				<Data>
					<Field name="TransformMe" value="'abcd=1234'" />
				</Data>
			</Action>

			<Action type="close" publisher="FilePubWrite" />

			<!-- Read and decode encoded file and slurp URL parameter to output in console -->
			<Action type="input" publisher="FilePubRead" >
				<DataModel name="InputModel" ref="Ex1" />
			</Action>

			<Action type="slurp" valueXpath="//InputModel//TransformMe" setXpath="//OutputModel//StringValue" />

			<Action type="output" publisher="ConsolePub">
				<DataModel name="OutputModel">
					<String name="StringValue" />
				</DataModel>
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex" name="ConsolePub"/>

		<Publisher class="File" name="FilePubWrite">
			<Param name="FileName" value="encoded.bin" />
		</Publisher>

		<Publisher class="File" name="FilePubRead">
			<Param name="FileName" value="encoded.bin" />
			<Param name="Overwrite" value="false" />
		</Publisher>
	</Test>
</Peach>
----


Output from this example.
----
> peach -1 --debug example.xml


[*] Test 'Default' starting with random seed 29519.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(43 bytes)
00000000   68 74 74 70 3A 2F 2F 70  65 61 63 68 66 75 7A 7A   http://peachfuzz
00000010   65 72 2E 63 6F 6D 2F 3F  71 3D 25 32 37 61 62 63   er.com/?q=%27abc
00000020   64 25 33 64 31 32 33 34  25 32 37                  d%3d1234%27
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.FilePublisher start()
Peach.Core.Publishers.FilePublisher open()
Peach.Core.Publishers.FilePublisher output(43 bytes)
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Close
Peach.Core.Publishers.FilePublisher close()
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Input
Peach.Core.Publishers.FilePublisher start()
Peach.Core.Publishers.FilePublisher open()
Peach.Core.Publishers.FilePublisher input()
Peach.Core.Cracker.DataCracker ------------------------------------
Peach.Core.Cracker.DataCracker DataModel 'InputModel' Bytes: 0/43, Bits: 0/344
Peach.Core.Cracker.DataCracker getSize: -----> DataModel 'InputModel'
Peach.Core.Cracker.DataCracker scan: DataModel 'InputModel'
Peach.Core.Cracker.DataCracker scan: String 'InputModel.DataElement_0' -> Pos: 0, Saving Token
Peach.Core.Cracker.DataCracker scan: String 'InputModel.DataElement_0' -> Pos: 208, Length: 208
Peach.Core.Cracker.DataCracker getSize: <----- Deterministic: ???
Peach.Core.Cracker.DataCracker Crack: DataModel 'InputModel' Size: <null>, Bytes: 0/43, Bits: 0/344
Peach.Core.Cracker.DataCracker ------------------------------------
Peach.Core.Cracker.DataCracker String 'InputModel.DataElement_0' Bytes: 0/43, Bits: 0/344
Peach.Core.Cracker.DataCracker getSize: -----> String 'InputModel.DataElement_0'
Peach.Core.Cracker.DataCracker scan: String 'InputModel.DataElement_0' -> Pos: 0, Saving Token
Peach.Core.Cracker.DataCracker scan: String 'InputModel.DataElement_0' -> Pos: 208, Length: 208
Peach.Core.Cracker.DataCracker getSize: <----- Size: 208
Peach.Core.Cracker.DataCracker Crack: String 'InputModel.DataElement_0' Size: 208, Bytes: 0/43, Bits: 0/344
Peach.Core.Dom.DataElement String 'InputModel.DataElement_0' value is: http://peachfuzzer.com/?q=
Peach.Core.Cracker.DataCracker ------------------------------------
Peach.Core.Cracker.DataCracker String 'InputModel.TransformMe' Bytes: 26/43, Bit s: 208/344
Peach.Core.Cracker.DataCracker getSize: -----> String 'InputModel.TransformMe'
Peach.Core.Cracker.DataCracker scan: String 'InputModel.TransformMe' -> Offset: 0, Unsized element
Peach.Core.Cracker.DataCracker lookahead: String 'InputModel.TransformMe'
Peach.Core.Cracker.DataCracker getSize: <----- Last Unsized: 136
Peach.Core.Cracker.DataCracker Crack: String 'InputModel.TransformMe' Size: 88, Bytes: 0/11, Bits: 0/88
Peach.Core.Dom.DataElement String 'InputModel.TransformMe' value is: 'abcd=1234'
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Slurp
Peach.Core.Dom.Action Slurp, setting OutputModel.StringValue from InputModel.TransformMe
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher output(11 bytes)
00000000   27 61 62 63 64 3D 31 32  33 34 27                  'abcd=1234'
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Publishers.FilePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()
Peach.Core.Publishers.FilePublisher stop()
Peach.Core.Publishers.FilePublisher stop()

[*] Test 'Default' finished.
----
==========================