== Introduction to Peach

Peach is a hybrid fuzzer, combining part of both mutation and generational fuzzing.

Fuzzing with Peach centers on the three M's of Peach: model, mutate, and monitor.

 * Model - We model the data format and data/state flow.
 * Mutate - The fuzzing engine uses the data and state models to mutate data intelligently, in preparation of sending the malformed data to the target.
 * Monitor - We monitor our test target and the test environment to identify fault conditions and to collect information used to investigate and remediate the faults.

A Peach fuzzing definition consists of the data and state models, monitoring declarations, and specifics about the test environment. Even though fuzzing definitions included with Peach have all of these components, you still need to describe the monitoring details, based on your test target and operating system.

Peach specifically targets data consumers. The data could be a file format, a network protocol, or an argument to an RPC interface.

Peach has the following high-level concepts:

Pit::
+
--
Fuzzing definitions in Peach are Pits.
Peach Pits are XML files that contain all the information Peach needs to perform a fuzzing operation.
This includes data models, state models, agent configurations (agents host the monitors), and test details.

Peach includes one or more licensed Pits purchased individually or in themed groups called Pit Packs. Peach offers Pits for more than 25 network protocols, and for some file formats. To fuzz with a Pit, you can run the Peach Web interface to configure the Pit, and then immediately use it.

If your needs extend beyond the available Pits offered by Peach, you can create a fuzzing definition for a custom file format, a proprietary network protocol, an embedded device, a kernel driver, and more.

--

Modeling::
+
--
Peach operates by fuzzing data and state models of the test targets. Because security testing (fuzzing) focuses on what happens when inappropriate data enters or appears in a system or when inappropriate state transitions occur, Peach focuses heavily on data modeling and state modeling.

For the average Peach user, most of the human time and energy now goes into analyzing fuzzing job results and fixing bugs. This is due to the availability of pre-made,
off-the-shelf Pits, and the Peach Web UI.

In most cases, gone are the days of time-consuming activities, such as defining and solidifying the data and state models of a fuzzing definition.
--

Publisher::
+
--
Publishers are I/O interfaces. 	They take abstract concepts such as input, output, and call (used in state modeling) and provide the actual transport or implementation.

Peach includes a number of Publishers so your pits and test configurations can perform the following tasks:

* write to files,
* connect to other devices using TCP, UDP or other network protocols,
* make web requests, or
* call COM objects.

If you need a custom Publisher, it is one of the simplest Peach components to create.
--

Fuzzing Strategy::
+
--
The fuzzing strategy is the logic that describes the test approach for a fuzzing session. The fuzzing strategy addresses some fundamental questions that impact a fuzzing session that include the following:

* Do we want Peach to test each element of the data and state models individually?
* Do we want Peach to test more than one element at a time?
* How many mutators do we want Peach to apply to each fuzzing element?
* Do we want to limit the number of iterations in the test session?

Peach includes several fuzzing strategies. They should be sufficient for the majority of users.
--

Mutators::
+
--
Mutators produce altered or mutated data. Some mutators use a reference data value and create new values based on the reference value. Other mutators generate new values from scratch, from a formula, or from a random number generator.

Mutators tend to contain very simple logic and should perform a single type of mutation. Some examples follow:

* Produce a number that is within 50 units from the supplied reference value.
* Produce a string that has a length between 1 and 10,000.
* Produce 500 random numbers between 0 and sizeof(int32).
--

Agents::
+
--
Agents are special Peach processes that can run locally or remotely, and host one or more Monitors or remote Publishers.
Agents are the basis for the robust monitor facility provided by the Peach Fuzzing Platform and allow for monitoring simple fuzzing configurations through very complex systems that have many tiers.

A Peach fuzzer can use zero or more agents.

Agents can be used for fault detection, data collection, and instrumentation of targets involved in the fuzzing run.
They do not host fuzzing engines themselves, nor do they play a part in parallel or distributed fuzzing.
Agents can also host Remote Publishers.

Agents can be written in any language. Peach Professional includes a built in agent and also basic implementations in several languages in the SDK.
--

Monitors::
+
--
Monitors run within Peach Agent processes and perform utility tasks such as taking captures of network traffic
during a fuzzing iteration, or attaching a debugger to a process to detect crashes, or even re-starting a network service if it crashes or stops.

Peach includes a number of monitors. Like Publishers, monitors are easy to write and integrate into the Peach environment.
--

Logger::
+
--
A logging facility saves crashes and fuzzing run information.

Peach comes with a file system logger by default.
--

The following sections dive deeper into all of these concepts and more.

// end
