#!/usr/bin/env python

if bld.env.DEST_OS is 'win32':
	variant = 'win_x86_%s' % bld.env.VARIANT
	if bld.env.SUBARCH is 'x64':
			variant =  'win_x64_%s' % bld.env.VARIANT

	clone = bld.clone_env(variant)
	if clone is not None:
		clone['CPPFLAGS'].append("/Wv:18")

bld(
	features = 'cxx cxxprogram debug network',
	source = bld.path.ant_glob('*.c'),
	target = 'SimpleHttpServer',
)


