<<<
[[Blob]]
== Blob

// Reviewed:
//  - 03/06/2014: Lynn
//  Edited comments

A Blob footnote:[Blob stands for "binary large object" a term used by databases to represent a column of binary data.] is used to represent binary data (array of bytes). Blobs are sized in bytes.

A Blob is always a child of a data element container such as xref:DataModel[DataModel] or xref:Block[Block]. By definition, the internal contents of a Blob is unknown. Consequently, Blobs are dumb fuzzed, as the list of applicable mutators below indicates.

Blobs can be used to create simple dumb fuzzers in Peach, see xref:Blob_Examples[examples].

=== Syntax

[source,xml]
----
<Blob valueType="hex" value="01 06 22 03" />
----

=== Attributes

_Required:_

There are no required attributes.

_Optional:_

xref:name[name]:: Element name
xref:length[length]:: The length of data in this element.
xref:lengthType[lengthType]:: Units of the length attribute. Defaults to "bytes". Can also be "chars", or "bits" where the number of bits is a multiple of 8. 

xref:value[value]:: Default value.
xref:valueType[valueType]:: Format of value attribute.
xref:occurs[occurs]::
	Actual occurrences of element. Defaults to 1.  +
	* Used to define arrays with static size.
	* Adding this attribute, even with a value of 1, converts the element to an array.

xref:minOccurs[minOccurs]::
	The minimum number of times this blob must occur. Defaults to 1.  +
	* Used to define arrays with variable size. Arrays defined by min/maxOccurs generally have a relation
	defined.
	* Adding this attribute, even with a value of 1, converts the element to an array.

xref:maxOccurs[maxOccurs]::
	The maximum number of times this blob can occur. Defaults to 1.  +
	* Used to define arrays with static size.
	* Adding this attribute, even with a value of 1, converts the element to an array.

xref:constraint[constraint]::
	A constraint in the form of an expression.  Used during data cracking.
xref:mutable[mutable]::
	Is the blob changeable (should it be fuzzed). Defaults to true.
xref:token[token]::
	This element should be treated as a token when parsing. Defaults to false.

=== Child Elements

xref:Analyzers[Analyzer]:: Analyzes current element post cracking, can dynamically change model.
xref:Fixup[Fixup]:: Performs dynamic transformations such as checksums and CRCs.
xref:Hint[Hint]:: Provides information to mutators.
xref:Placement[Placement]:: Relocates an element after it has been cracked.
xref:Transformer[Transformer]:: Performs static transformations such as compression or encoding.

=== Mutators

The following mutators operate on this element type.


_Enabled when element is marked as an array_

xref:Mutators_ArrayNumericalEdgeCasesMutator[ArrayNumericalEdgeCasesMutator]:: This mutator grows and shrinks an array to counts based on numerical edge cases.
xref:Mutators_ArrayRandomizeOrderMutator[ArrayRandomizeOrderMutator]:: This mutator randomizes the order of items in an array.
xref:Mutators_ArrayReverseOrderMutator[ArrayReverseOrderMutator]:: This mutator reverses the order of items in an array.
xref:Mutators_ArrayVarianceMutator[ArrayVarianceMutator]:: This mutator grows and shrinks an array to a variance of counts based on the current size.

_Used for all data elements_

xref:Mutators_DataElementBitFlipper[DataElementBitFlipper]:: This mutator produces test cases by flipping bits in the output value.
xref:Mutators_DataElementDuplicate[DataElementDuplicate]:: This mutator duplicates data elements.
xref:Mutators_DataElementRemove[DataElementRemove]:: This mutator removes data elements.
xref:Mutators_DataElementSwapNear[DataElementSwapNear]:: This mutator swaps data elements.
xref:Mutators_SampleNinjaMutator[SampleNinjaMutator]:: This mutator combines data elements from different data sets.

_Enabled when element is part of a size relation_

xref:Mutators_SizedDataEdgeCase[SizedDataEdgeCase]:: This mutator causes the data portion of a relation to be sized as numerical edge cases.
xref:Mutators_SizedDataVariance[SizedDataVariance]:: This mutator causes the data portion of a relation to be sized as numerical variances.
xref:Mutators_SizedEdgeCase[SizedEdgeCase]:: This mutator changes both sides of the relation (data and value) to match numerical edge cases.
xref:Mutators_SizedVariance[SizedVariance]:: This mutator changes both sides of the relation (data and value) to match numerical variances of the current size.

_Specific to this element type_

xref:Mutators_BlobChangeFromNull[BlobChangeFromNull]:: This mutator produces test cases in which null bytes in a xref:Blob[Blob] element are changed to a non-null value.
xref:Mutators_BlobChangeRandom[BlobChangeRandom]:: This mutator produces test cases by changing random selections of bytes to random value.
xref:Mutators_BlobChangeSpecial[BlobChangeSpecial]:: This mutator produces test cases by changing random selections of bytes to one of 0x00, 0x01, 0xFE, 0xFF.
xref:Mutators_BlobChangeToNull[BlobChangeToNull]:: This mutator produces test cases by changing a random number of bytes to 0x00.
xref:Mutators_BlobExpandSingleIncrementing[BlobExpandSingleIncrementing]:: This mutator produces test cases by expanding the size of the blob using incrementing values.
xref:Mutators_BlobExpandAllRandom[BlobExpandAllRandom]:: This mutator produces test cases by expanding the size of the blob using random values.
xref:Mutators_BlobExpandSingleRandom[BlobExpandSingleRandom]:: This mutator produces test cases by expanding the size of the blob using a single random byte (repeated as needed).
xref:Mutators_BlobExpandZero[BlobExpandZero]:: This mutator produces test cases by expanding the blob using null values.
xref:Mutators_BlobReduce[BlobReduce]:: This mutator produces test cases by reducing the size of the blob by a random amount.
xref:Mutators_ExtraValues[ExtraValues]:: This mutator allows providing extra test case values on a per-data element basis.


[[Blob_Examples]]
=== Examples

.Dumb file fuzzing
==========================
This is an example of dumb file fuzzing. Peach cracks the data from _sample.png_ into a Blob. This is considered dumb fuzzing because the data model does not fully describe the structure of the data being fuzzed.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach>

	<DataModel name="TheDataModel">
		<Blob />
	</DataModel>

	<!-- Define a simple state machine that will write the file and
		then launch a program using the FileWriter and DebuggerLaucher publishers -->
	<StateModel name="State" initialState="Initial">
		<State name="Initial">

			<!-- Write out contents of file. -->
			<Action type="output">
				<DataModel ref="TestTemplate" />
				<Data fileName="sample.png" />
			</Action>

			<!-- Close file -->
			<Action type="close" />

			<!-- Launch the file consumer -->
			<Action type="call" method="ScoobySnacks" publisher="Peach.Agent"/>

		</State>
	</StateModel>

	<!-- Setup a local agent that will monitor for faults -->
	<Agent name="LocalAgent">
		<Monitor class="WindowsDebugger">

			<!-- The command line to run.  Notice the filename provided matched up
				to what is provided below in the Publisher configuration -->
			<Param name="Executable" value="c:\windows\system32\mspaint.exe" />
			<Param name="Arguments" value="fuzzfile.bin" />

			<!-- This parameter will cause the debugger to wait for an action-call in
				the state model with a method="ScoobySnacks" before running
				program.

				Note: You will also need to add a parameter to the publisher called
				    "debugger" and set it to "true"!
				-->
			<Param name="StartOnCall" value="ScoobySnacks" />

		</Monitor>
	</Agent>

	<Test name="Default">
		<Agent ref="LocalAgent" />
		<StateModel ref="State"/>

		<!-- Configure our publisher with correct filename to write too -->
		<Publisher class="File">
			<Param name="FileName" value="fuzzfile.bin" />
		</Publisher>

		<!-- Configure a logger to store collected information -->	</Test>
</Peach>
----
==========================

.Defining a Blob with a default value
==========================
A blob with a default value. Providing a default value does not set a fixed length unless the token="true" attribute is used.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="Ex1">
    <Blob name="Unknown1" valueType="hex" value="AA BB CC DD" />
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="output" publisher="ConsolePub">
        <DataModel ref="Ex1" />
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>

    <Publisher class="ConsoleHex" name="ConsolePub"/>  </Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug example.xml

[*] Test 'Default' starting with random seed 46616.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(4 bytes)
00000000   AA BB CC DD                                        ????
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----

.Using a Blob as part of a size relationship

A blob with size-of relationship:

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="Ex1">
    <Number name="LengthOfData" size="32">
      <Relation type="size" of="Data" />
    </Number>

    <Blob name="Data" valueType="hex" value="AA BB CC DD" />
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="output" publisher="ConsolePub">
        <DataModel ref="Ex1" />
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>

    <Publisher class="ConsoleHex" name="ConsolePub"/>  </Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug example.xml

[*] Test 'Default' starting with random seed 18508.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(8 bytes)
00000000   04 00 00 00 AA BB CC DD                            ????????
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
==========================
