<<<
[[Double]]
== Double

The _Double_ element defines a floating-point number of 32 or 64 bits. Floating point values are packed into a byte representation with a byte order of little or big endian.

The Double element is a child element of xref:DataModel[DataModel], xref:Block[Block], xref:Sequence[Sequence] or xref:Choice[Choice].

NOTE: The floating point representation used for the _Double_ element is based on the IEEE 754 floating point specification. For floating point values not conforming to IEEE 754, consider using a xref:Blob[Blob] data type as an alternative.

=== Syntax

[source,xml]
----
<Double name="Precision" size="64" endian="big"/>
----

=== Attributes

_Required:_

xref:size[size]::
	Size of floating point number in bits. Valid options are 32 or 64.

_Optional:_

xref:name[name]::
	Name of the floating point number.
xref:value[value]::
	The default value to assign to the floating point number.
xref:valueType[valueType]::
	The representation of the value.
	Valid options are string and hex.
xref:token[token]::
	This element is treated as a token when parsing, defaults to false. Valid options true and false.
xref:endian[endian]::
	Byte order of the number, defaults to little. Valid options are big, little, and network.
	Network is the same as big.
xref:constraint[constraint]::
	A constraint in the form of a python expression.
	Used during data cracking.
xref:mutable[mutable]::
	Is data element changeable (should it be mutated during fuzzing), defaults to true.
	Valid options true and false.
xref:minOccurs[minOccurs]::
	The minimum number of times this number must occur.
	Defaults to 1.
	Valid options are a positive integer value.
xref:maxOccurs[maxOccurs]::
	The maximum number of times this number can occur.
	No default.
	Valid options are a positive integer value.
xref:occurs[occurs]::
	The actual number of times this number occurs.
	Defaults to 1.

=== Child Elements

xref:Analyzers[Analyzer]:: Analyze current element post cracking, can dynamically change model.
xref:Fixup[Fixup]:: Dynamic transformations such as checksums and CRCs.
xref:Hint[Hint]:: Provide information to mutators.
xref:Placement[Placement]:: Relocate an element after it has been cracked.
xref:Relation[Relation]:: Modeling of relationships in the data (such as comparisons)
xref:Transformer[Transformer]:: Static transformations such as compression or encoding.

=== Mutators

The following mutators will operate on this element type:


_Enabled when element is marked as an array_

xref:Mutators_ArrayNumericalEdgeCasesMutator[ArrayNumericalEdgeCasesMutator]:: This mutator will grow and shrink an array to counts based on numerical edge cases.
xref:Mutators_ArrayRandomizeOrderMutator[ArrayRandomizeOrderMutator]:: This mutator will randomize the order of items in an array.
xref:Mutators_ArrayReverseOrderMutator[ArrayReverseOrderMutator]:: This mutator will reverse the order of items in an array.
xref:Mutators_ArrayVarianceMutator[ArrayVarianceMutator]:: This mutator will grow and shrink an array to a variance of counts based on the current size.

_Used for all data elements_

xref:Mutators_DataElementBitFlipper[DataElementBitFlipper]:: This mutator will produce test cases by flipping bits in the output value.
xref:Mutators_DataElementDuplicate[DataElementDuplicate]:: This mutator will duplicate data elements.
xref:Mutators_DataElementRemove[DataElementRemove]:: This mutator will remove data elements.
xref:Mutators_DataElementSwapNear[DataElementSwapNear]:: This mutator will swap data elements.
xref:Mutators_SampleNinjaMutator[SampleNinjaMutator]:: This mutator will combine data elements from different data sets.

_Enabled when element is part of a size relation_

xref:Mutators_SizedDataEdgeCase[SizedDataEdgeCase]:: This mutator will cause the data portion of a relation to be sized as numerical edge cases.
xref:Mutators_SizedDataVariance[SizedDataVariance]:: This mutator will cause the data portion of a relation to be sized as numerical variances.
xref:Mutators_SizedEdgeCase[SizedEdgeCase]:: This mutator will change both sides of the relation (data and value) to match numerical edge cases.
xref:Mutators_SizedVariance[SizedVariance]:: This mutator will change both sides of the relation (data and value) to match numerical variances of the current size.

_Specific to this element type_

xref:Mutators_DoubleRandom[DoubleRandom]:: This mutator will produce random values from the available numerical space.
xref:Mutators_DoubleVariance[DoubleVariance]:: This mutator will produce values near the current value of a number.


=== Examples

.Size
==========================
Produce 32 bit (4 byte) floating point number with a default value of 5.1:

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">
	<DataModel name="DoubleExample1">
		<Double name="Hi51" value="5.1" size="32"/>
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="DoubleExample1"/>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent" />

	<Test name="Default">
		<Agent ref="TheAgent"/>

		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex"/>
	</Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug DoubleExample1.xml

[*] Test 'Default' starting with random seed 12232.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.StateModel Run(): Changing to state "Initial".
Peach.Core.Dom.Action Run(Action): Output
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(4 bytes)
00000000   33 33 A3 40                                        33.@ <1>
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
<1> The 32 bit little endian value 5.1

To use 64 bits (four byte) change the size to 64.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

	<DataModel name="DoubleExample2">
		<Double name="Hi51" value="5.1" size="64"/>
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="DoubleExample2"/>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent" />

	<Test name="Default">
		<Agent ref="TheAgent"/>

		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex"/>
	</Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug DoubleExample2.xml

[*] Test 'Default' starting with random seed 51105.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.StateModel Run(): Changing to state "Initial".
Peach.Core.Dom.Action Run(Action): Output
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(8 bytes)
00000000   66 66 66 66 66 66 14 40                            ffffff.@ <1>
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
<1> The 64 bit little endian value 5.1

*NOTE:* Double elements use the `size` attribute which is, by default, the size in
*bits*. `Double` elements do not accept `length` attribute used by other elements.
==========================

.Endian
==========================

To change the endianness of the floating point number set the endian attribute. Endianness defines in which order the bytes are the least or most significant.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

	<DataModel name="DoubleExample3">
		<Double name="big" value="10.0" size="64" endian="big" />
	</DataModel>

	<DataModel name="DoubleExample4">
		<Double name="little" value="10.0" size="64" endian="little" />
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="DoubleExample3"/>
			</Action>
			<Action type="output">
				<DataModel ref="DoubleExample4"/>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent" />

	<Test name="Default">
		<Agent ref="TheAgent"/>

		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex"/>
	</Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug DoubleEndianExample.xml

[*] Test 'Default' starting with random seed 35381.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.StateModel Run(): Changing to state "Initial".
Peach.Core.Dom.Action Run(Action): Output
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(8 bytes)
00000000   40 24 00 00 00 00 00 00                            @$...... <1>
Peach.Core.Dom.Action Run(Action_1): Output
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Publishers.ConsolePublisher output(8 bytes)
00000000   00 00 00 00 00 00 24 40                            ......$@ <2>
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
<1> Big endian outputs the bytes in the order
<2> Little endian outputs the bytes in the order

Note, however, that endian-ness doesn't have any impact on output if the `valueType`
is `"hex"`:

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

	<DataModel name="DoubleExample5">
		<Double name="abcd" valueType="hex" value="ABCDEF01ABCDEF01" size="64" endian="little" />
	</DataModel>

	<DataModel name="DoubleExample6">
		<Double name="abcd" valueType="hex" value="ABCDEF01ABCDEF01" size="64" endian="big" />
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="DoubleExample5"/>
			</Action>
			<Action type="output">
				<DataModel ref="DoubleExample6"/>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent" />

	<Test name="Default">
		<Agent ref="TheAgent"/>

		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex"/>
	</Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug NumberEndianExample.xml

[*] Test 'Default' starting with random seed 53121.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.StateModel Run(): Changing to state "Initial".
Peach.Core.Dom.Action Run(Action): Output
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(8 bytes)
00000000   AB CD EF 01 AB CD EF 01                            ........   <1>
Peach.Core.Dom.Action Run(Action_1): Output
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Publishers.ConsolePublisher output(8 bytes)
00000000   AB CD EF 01 AB CD EF 01                            ........   <2>
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
<1> For little we see the expected output
<2> For big endian, nothing changes

When the attribute `valueType` is set to `"hex"` this indicates that
the ordering is exactly as specified. The `endian` attribute still
impacts mutation and input parsing.
==========================
