<<<
[[JsonString]]
== JsonString

Represents a JSON string of Unicode characters.

All strings are encoded prior to output according to the JSON specification.

Strings can hold numbers that are stored in a string format.
When strings contain a number,
Peach additionally uses numerical mutators to mutate the strings.

The JsonString element is a child element of
xref:DataModel[DataModel],
xref:Block[Block],
xref:Sequence[Sequence],
xref:JsonObject[JsonObject],
xref:JsonArray[JsonArray],
or xref:Choice[Choice].

=== Syntax

[source,xml]
----
<JsonString value="Hello World!" />

<JsonObject>
    <JsonString propertyName="name" value="Peach" />
</JsonObject>
----

=== Attributes

_Required:_

None.

_Optional:_

xref:name[name]::
    Name of the element.

propertyName::
    Property name for element when child of xref:JsonObject[JsonObject].

isNull::
    Is this elements value null. Json output will be +null+ instead of +""+ or value.
type:: Type controls the output encoding allowing both traditional json and also binary json (bson). Supported values: 'json' or 'bson'. Defaults to 'json'.

xref:value[value]:: The default value, defaults to "".

xref:valueType[valueType]:: Format of the _value_ attribute, defaults to string.

xref:token[token]::
	This element should be treated as a token when parsing. Valid values are true and false, defaults to false.	+
	This attribute is primarily used to assist in cracking strings when consuming input in a model.

xref:mutable[mutable]:: Should this data element be mutated (or, is it changeable)? Valid values are true and false, defaults to true.

=== Child Elements

xref:Analyzers[Analyzer]:: Attaches an analyzer to this element
xref:Fixup[Fixup]:: Performs dynamic transformations such as checksums and CRCs.
xref:Hint[Hint]:: Provides information to mutators.
xref:Placement[Placement]:: Relocates an element after it has been cracked.
xref:Relation[Relation]:: Identifies a type of relationship with another data element (such as count).
xref:Transformer[Transformer]:: Performs static transformations such as compression or encoding.

=== Mutators

The following mutators operate on this element type:

_Used for all data elements_

xref:Mutators_DataElementDuplicate[DataElementDuplicate]:: This mutator duplicates data elements.
xref:Mutators_DataElementRemove[DataElementRemove]:: This mutator removes data elements.
xref:Mutators_DataElementSwapNear[DataElementSwapNear]:: This mutator swaps data elements.
xref:Mutators_SampleNinjaMutator[SampleNinjaMutator]:: This mutator combines data elements from different data sets.

_Enabled when element is part of a size relation_

xref:Mutators_SizedDataEdgeCase[SizedDataEdgeCase]:: This mutator causes the data portion of a relation to be sized as numerical edge cases.
xref:Mutators_SizedDataVariance[SizedDataVariance]:: This mutator causes the data portion of a relation to be sized as numerical variances.
xref:Mutators_SizedEdgeCase[SizedEdgeCase]:: This mutator changes both sides of the relation (data and value) to match numerical edge cases.
xref:Mutators_SizedVariance[SizedVariance]:: This mutator changes both sides of the relation (data and value) to match numerical variances of the current size.

_Specific to this element type_

xref:Mutators_ExtraValues[ExtraValues]:: This mutator provides extra test case values on a per-data element basis.
xref:Mutators_StringAsciiRandom[StringAsciiRandom]:: This mutator generates strings with random ASCII characters.
xref:Mutators_StringCaseLower[StringCaseLower]:: This mutator generates a lower case version of the current value.
xref:Mutators_StringCaseRandom[StringCaseRandom]:: This mutator generates a randomized case version of the current value.
xref:Mutators_StringCaseUpper[StringCaseUpper]:: This mutator generates an upper case version of the current value.
xref:Mutators_StringLengthEdgeCase[StringLengthEdgeCase]:: This mutator generates strings with lengths based on numerical edge cases.
xref:Mutators_StringLengthVariance[StringLengthVariance]:: This mutator generates strings with lengths based on a variance around the current string length.
xref:Mutators_StringList[StringList]:: This mutator allows providing a list of strings to use as test cases on an element by element basis.
xref:Mutators_StringStatic[StringStatic]:: This mutator generates test cases using a static set of strings.
xref:Mutators_StringUnicodeAbstractCharacters[StringUnicodeAbstractCharacters]:: This mutator generates Unicode strings using abstract characters.
xref:Mutators_StringUnicodeFormatCharacters[StringUnicodeFormatCharacters]:: This mutator generates Unicode strings using format characters.
xref:Mutators_StringUnicodeInvalid[StringUnicodeInvalid]:: This mutator generates Unicode strings using invalid characters.
xref:Mutators_StringUnicodeNonCharacters[StringUnicodeNonCharacters]:: This mutator generates Unicode strings using non-characters.
xref:Mutators_StringUnicodePlane0[StringUnicodePlane0]:: This mutator generates Unicode strings using Plane 0 characters.
xref:Mutators_StringUnicodePlane1[StringUnicodePlane1]:: This mutator generates Unicode strings using Plane 1 characters.
xref:Mutators_StringUnicodePlane14[StringUnicodePlane14]:: This mutator generates Unicode strings using Plan 14 characters.
xref:Mutators_StringUnicodePlane15And16[StringUnicodePlane15And16]:: This mutator generates Unicode strings using Plane 15 and 16 characters.
xref:Mutators_StringUnicodePlane2[StringUnicodePlane2]:: This mutator generates Unicode strings using Plane 2 characters.
xref:Mutators_StringUnicodePrivateUseArea[StringUnicodePrivateUseArea]:: This mutator generates Unicode characters from the private use area.
xref:Mutators_StringXmlW3C[StringXmlW3C]:: This mutator provides the W3C XML parser unit tests. Must be specifically enabled.

=== Examples

.Simple String
====================

This example outputs a string that is part of a xref:JsonObject[JsonObject].

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

	<DataModel name="TheDataModel">
        <JsonObject>
		  <JsonString propertyName="phrase" value="Hello World!" />
        </JsonObject>
	</DataModel>

	<StateModel name="TheStateModel" initialState="InitialState" >
		<State name="InitialState">
			<Action type="output">
				<DataModel ref="TheDataModel"/>
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheStateModel"/>

		<Publisher class="ConsoleHex" />
	</Test>
</Peach>
----

Produces the following output:

----
> peach -1 --debug example.xml

[*] Web site running at: http://10.0.1.57:8888/

[*] Test 'Default' starting with random seed 51346.
Peach.Pro.Core.Loggers.JobLogger Writing debug.log to: c:\peach\Logs\example.xml_20160215191651\debug.log

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.StateModel Run(): Changing to state "InitialState".
Peach.Core.Dom.Action Run(Action): Output
Peach.Pro.Core.Publishers.ConsolePublisher start()
Peach.Pro.Core.Publishers.ConsolePublisher open()
Peach.Pro.Core.Publishers.ConsolePublisher output(25 bytes)
00000000   7B 22 70 68 72 61 73 65  22 3A 22 48 65 6C 6C 6F   {"phrase":"Hello
00000010   20 57 6F 72 6C 64 21 22  7D                         World!"}
Peach.Pro.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Pro.Core.Publishers.ConsolePublisher stop()
Peach.Core.Engine EndTest: Stopping all agents and monitors

[*] Test 'Default' finished.
----
====================

.Null String
====================

In this example our initial value for our JsonString element is null. During testing this field's value
will be mutated to string values.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

	<DataModel name="TheDataModel">
        <JsonObject>
		  <JsonString propertyName="phrase" isNull="true" />
        </JsonObject>
	</DataModel>

	<StateModel name="TheStateModel" initialState="InitialState" >
		<State name="InitialState">
			<Action type="output">
				<DataModel ref="TheDataModel"/>
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheStateModel"/>

		<Publisher class="ConsoleHex" />
	</Test>
</Peach>
----

Produces the following output:

----
> peach -1 --debug example.xml

[*] Web site running at: http://10.0.1.57:8888/

[*] Test 'Default' starting with random seed 29586.
Peach.Pro.Core.Loggers.JobLogger Writing debug.log to: c:\peach\Logs\example.xml_20160215192237\debug.log

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.StateModel Run(): Changing to state "InitialState".
Peach.Core.Dom.Action Run(Action): Output
Peach.Pro.Core.Publishers.ConsolePublisher start()
Peach.Pro.Core.Publishers.ConsolePublisher open()
Peach.Pro.Core.Publishers.ConsolePublisher output(15 bytes)
00000000   7B 22 70 68 72 61 73 65  22 3A 6E 75 6C 6C 7D      {"phrase":null}
Peach.Pro.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Pro.Core.Publishers.ConsolePublisher stop()
Peach.Core.Engine EndTest: Stopping all agents and monitors

[*] Test 'Default' finished.
----
====================

.String in JsonArray
====================

This example outputs a string that is part of a xref:JsonArray[JsonArray].  Note that we do not
specify +propertyName+ in this case.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

	<DataModel name="TheDataModel">
        <JsonArray>
		  <JsonString value="Hello World!" />
        </JsonArray>
	</DataModel>

	<StateModel name="TheStateModel" initialState="InitialState" >
		<State name="InitialState">
			<Action type="output">
				<DataModel ref="TheDataModel"/>
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheStateModel"/>

		<Publisher class="ConsoleHex" />
	</Test>
</Peach>
----

Produces the following output:

----
> peach -1 --debug example.xml

[*] Web site running at: http://10.0.1.57:8888/

[*] Test 'Default' starting with random seed 4074.
Peach.Pro.Core.Loggers.JobLogger Writing debug.log to: c:\peach\example.xml_20160215192532\debug.log

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.StateModel Run(): Changing to state "InitialState".
Peach.Core.Dom.Action Run(Action): Output
Peach.Pro.Core.Publishers.ConsolePublisher start()
Peach.Pro.Core.Publishers.ConsolePublisher open()
Peach.Pro.Core.Publishers.ConsolePublisher output(16 bytes)
00000000   5B 22 48 65 6C 6C 6F 20  57 6F 72 6C 64 21 22 5D   ["Hello World!"]
Peach.Pro.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Pro.Core.Publishers.ConsolePublisher stop()
Peach.Core.Engine EndTest: Stopping all agents and monitors

[*] Test 'Default' finished.
----
====================

// end
