<<<
[[Number]]
== Number

The Number element defines a binary number of any arbitrary bit size from 1 to 64. Binary numbers are packed into a byte representation with a byte order of little-endian or big-endian.

The Number element should not be used for character-based numbers, or ASCII numbers. Instead, use a xref:String[String] element.

The Number element is a child element of xref:DataModel[DataModel], xref:Block[Block], or xref:Choice[Choice].

See also xref:VarNumber[VarNumber] and xref:String[String].

NOTE: While Peach supports unaligned data structures, using unaligned data incurs a performance penalty. The penalty stems from bit slicing that occurs behind the scenes.

TIP: In Peach, two attributes are commonly used to indicate size or length of an element, _size_ and _length_. The _size_ attribute always refers to the number of bits in an element. In contrast, the _length_ attribute refers to the number of bytes of an element.

=== Syntax

[source,xml]
----
<Number name="Almonds" size="32" endian="big" signed="false" />
----

=== Attributes

_Required:_

xref:size[size]::
	Size of number in bits.  Valid options are 1 through 64.

_Optional:_

xref:name[name]::
	Name of the number.
xref:value[value]::
	The default value to assign to the number.
xref:valueType[valueType]::
	The representation of the value. Valid options are string and hex.
xref:token[token]::
	This element is treated as a token when parsing. Valid values are true and false, defaults to false.
xref:endian[endian]::
	Byte order of the number. Valid options are big, little, and network. Network is an alias for big. The default value is little.
xref:signed[signed]::
	The number is signed or unsigned. Valid values are true and false, defaults to false.
xref:constraint[constraint]::
	A constraint in the form of a python expression. Used during data cracking.
xref:mutable[mutable]::
	Is data element changeable (should it be mutated during fuzzing). Valid values are true and false, defaults to true.

xref:minOccurs[minOccurs]::
	The minimum number of times this element must occur. Defaults to 1.  +
	* Used to define arrays with variable size. Arrays defined by min/maxOccurs generally have a relation
	defined.
	* Adding this attribute, even with a value of 1, converts the element to an array.

xref:maxOccurs[maxOccurs]::
	The maximum number of times this element can occur. +
	* Used to define arrays with static size.
	* Adding this attribute, even with a value of 1, converts the element to an array.

xref:occurs[occurs]::
	Actual occurrences of element. Defaults to 1.  +
	* Used to define arrays with static size.
	* Adding this attribute, even with a value of 1, converts the element to an array.

=== Child Elements

xref:Analyzers[Analyzer]:: Analyzes current element post cracking, can dynamically change model.
xref:Fixup[Fixup]:: Performs dynamic transformations such as checksums and CRCs.
xref:Hint[Hint]:: Provides information to mutators.
xref:Placement[Placement]:: Relocates an element after it has been cracked.
xref:Relation[Relation]:: Identifies a type of relationship with another data element (such as count).
xref:Transformer[Transformer]:: Performs static transformations such as compression or encoding.

=== Mutators

The following mutators operate on this element type:


_Enabled when element is marked as an array_

xref:Mutators_ArrayNumericalEdgeCasesMutator[ArrayNumericalEdgeCasesMutator]:: This mutator grows and shrinks an array to counts based on numerical edge cases.
xref:Mutators_ArrayRandomizeOrderMutator[ArrayRandomizeOrderMutator]:: This mutator randomizes the order of items in an array.
xref:Mutators_ArrayReverseOrderMutator[ArrayReverseOrderMutator]:: This mutator reverses the order of items in an array.
xref:Mutators_ArrayVarianceMutator[ArrayVarianceMutator]:: This mutator grows and shrinks an array to a variance of counts based on the current size.

_Used for all data elements_

xref:Mutators_DataElementBitFlipper[DataElementBitFlipper]:: This mutator produces test cases by flipping bits in the output value.
xref:Mutators_DataElementDuplicate[DataElementDuplicate]:: This mutator duplicates data elements.
xref:Mutators_DataElementRemove[DataElementRemove]:: This mutator removes data elements.
xref:Mutators_DataElementSwapNear[DataElementSwapNear]:: This mutator swaps data elements.
xref:Mutators_SampleNinjaMutator[SampleNinjaMutator]:: This mutator combines data elements from different data sets.

_Enabled when element is part of a size relation_

xref:Mutators_SizedDataEdgeCase[SizedDataEdgeCase]:: This mutator causes the data portion of a relation to be sized as numerical edge cases.
xref:Mutators_SizedDataVariance[SizedDataVariance]:: This mutator causes the data portion of a relation to be sized as numerical variances.
xref:Mutators_SizedEdgeCase[SizedEdgeCase]:: This mutator changes both sides of the relation (data and value) to match numerical edge cases.
xref:Mutators_SizedVariance[SizedVariance]:: This mutator changes both sides of the relation (data and value) to match numerical variances of the current size.

_Specific to this element type_

xref:Mutators_ExtraValues[ExtraValues]:: This mutator provides extra test case values on a per-data element basis.

xref:Mutators_NumberEdgeCase[NumberEdgeCase]:: This mutator produces numerical edge cases for integer values.
xref:Mutators_NumberRandom[NumberRandom]:: This mutator produces random values from the available numerical space.
xref:Mutators_NumberVariance[NumberVariance]:: This mutator produces values near the current value of a number.


=== Examples

.Size
==========================
Produce a 32-bit (4-byte) number with a default value of 5.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">
	<DataModel name="NumberExample1">
		<Number name="Hi5" value="5" size="32"/>
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="NumberExample1"/>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent" />

	<Test name="Default">
		<Agent ref="TheAgent"/>

		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex"/>
	</Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug NumberExample1.xml

[*] Test 'Default' starting with random seed 6226.
Peach.Core.MutationStrategies.RandomStrategy Iteration: Switch iteration, setting controlIteration and controlRecordingIteration.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Updating action to original data model
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(4 bytes)
00000000   05 00 00 00                                        ????            <1>
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
<1> The 32-bit, little-endian value is 5.

Change the previous example to use a 16-bit (two-byte) number by adjusting the size to 16.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

	<DataModel name="NumberExample2">
		<Number name="Hi5" value="5" size="16"/>
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="NumberExample2"/>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent" />

	<Test name="Default">
		<Agent ref="TheAgent"/>

		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex"/>
	</Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug NumberExample2.xml

[*] Test 'Default' starting with random seed 51118.
Peach.Core.MutationStrategies.RandomStrategy Iteration: Switch iteration, setting controlIteration and controlRecordingIteration.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Updating action to original data model
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(2 bytes)
00000000   05 00                                              ??              <1>
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
<1> The 16 bit little endian value 5

*NOTE:* Numbers use the `size` attribute which specifies the number of *bits*. _Number_ elements do not accept the `length` attribute used by other elements.
==========================

.Byte Alignment
==========================
While many data structures are byte aligned, some are not. This example arbitrarily defines sizes that do not 
fall on byte boundaries.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

	<DataModel name="ByteAlignmentExample1">
		<Number value="2" size="3" />
		<Number value="12" size="5" />
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="ByteAlignmentExample1"/>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent" />
	<Test name="Default">
		<Agent ref="TheAgent"/>

		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex"/>
	</Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug ByteAlignExample.xml

[*] Test 'Default' starting with random seed 41464.
Peach.Core.MutationStrategies.RandomStrategy Iteration: Switch iteration, setting controlIteration and controlRecordingIteration.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Updating action to original data model
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(1 bytes)
00000000   4C                                                 L               <1>
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()
----
<1> Two numbers are compacted into one byte.

The first number is three bits with the value `"2"`. This number
becomes the first three bits of the byte. The remaining five bits are
appended to the left.

In Python this could be written as the following:

----
>>> hex((2 << 5) + 12)
'0x4c'
----

Input parsing is simply the inverse.

----
>>> input_byte = 0x4C
>>> offset = 5
>>> (input_byte >> offset)
2																				<1>
>>> input_byte & (-1 + (2**offset))
12																			<2>
----
<1> The first byte is bit-shifted using the size of the second.
<2> By masking off the first number, we get the second.
==========================


.Endian
==========================

To change the endian-ness of the number, set the endian attribute. Endian-ness defines the order of the least-significant or most-significant bytes. 

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

	<DataModel name="NumberExample6">
		<Number name="abcd" value="52651" size="16" signed="false" endian="big" />
	</DataModel>

	<DataModel name="NumberExample7">
		<Number name="abcd" value="52651" size="16" signed="false" endian="little" />
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="NumberExample6"/>
			</Action>
			<Action type="output">
				<DataModel ref="NumberExample7"/>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent" />

	<Test name="Default">
		<Agent ref="TheAgent"/>

		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex"/>
	</Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug NumberEndianExample.xml

[*] Test 'Default' starting with random seed 16220.
Peach.Core.MutationStrategies.RandomStrategy Iteration: Switch iteration, setting controlIteration and controlRecordingIteration.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Updating action to original data model
Peach.Core.Dom.Action Updating action to original data model
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(2 bytes)
00000000   CD AB                                              ??              <1>
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher output(2 bytes)
00000000   AB CD                                              ??              <2>
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
<1> Little endian outputs the bytes in the order  CD AB
<2> Big endian outputs the bytes in the order  AB CD

Note, however, that endian-ness doesn't have any impact on output if the `valueType`
is `"hex"`:

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

	<DataModel name="NumberExample6">
		<Number name="abcd" valueType="hex" value="ABCD" size="16" signed="false" endian="little" />
	</DataModel>

	<DataModel name="NumberExample7">
		<Number name="abcd" valueType="hex" value="ABCD" size="16" signed="false" endian="big" />
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="NumberExample6"/>
			</Action>
			<Action type="output">
				<DataModel ref="NumberExample7"/>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent" />

	<Test name="Default">
		<Agent ref="TheAgent"/>

		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex"/>
	</Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug NumberEndianExample.xml

[*] Test 'Default' starting with random seed 37516.
Peach.Core.MutationStrategies.RandomStrategy Iteration: Switch iteration, setting controlIteration and controlRecordingIteration.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Updating action to original data model
Peach.Core.Dom.Action Updating action to original data model
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(2 bytes)
00000000   AB CD                                              ??              <1>
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher output(2 bytes)
00000000   AB CD                                              ??							<2>
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
<1> For little endian, the expected output displays.
<2> For big endian, nothing changes.

When the attribute `valueType` is set to `"hex"`, the ordering is exactly as specified. 
The `endian` attribute still impacts mutation and input parsing.
==========================


.Signed and Unsigned
==========================

To indicate value is signed, set the `signed` attribute equal to `"true"`. The default is false.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

	<DataModel name="UnsignedExample">
		<Number name="UnsignedInt" value="4294967295" size="32"/>
	</DataModel>

	<DataModel name="SignedExample">
		<Number name="SignedInt" value="-2147483648" size="32" signed="true"/>
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="UnsignedExample"/>
			</Action>
			<Action type="output">
				<DataModel ref="SignedExample"/>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent" />

	<Test name="Default">
		<Agent ref="TheAgent"/>

		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex"/>
	</Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug NumberExample3.xml

[*] Test 'Default' starting with random seed 64304.
Peach.Core.MutationStrategies.RandomStrategy Iteration: Switch iteration, setting controlIteration and controlRecordingIteration.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Updating action to original data model
Peach.Core.Dom.Action Updating action to original data model
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(4 bytes)
00000000   FF FF FF FF                                        ????            <1>
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher output(4 bytes)
00000000   FF FF FF FF                                        ????            <2>
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
<1> Output of unsigned 4294967295
<2> Output of signed -1
==========================

.Value Type
==========================
The valueType defines how to interpret the value attribute. Valid options are '"string"' and '"hex"'. The default value is 'string'.

To assign a value of 1000 to MyValue, use the default `valueType` of `"string"`. The `"string"` type supports 
both decimal and hexadecimal values.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

	<DataModel name="NumberTypeExample1">
		<Number name="MyValue" value="1000" valueType="string" size="16" signed="false" />
	</DataModel>

	<DataModel name="NumberTypeExample2">
		<Number name="MyValue" value="0x03e8" valueType="string" size="16" signed="false" />
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="NumberTypeExample1"/>
			</Action>
			<Action type="output">
				<DataModel ref="NumberTypeExample2"/>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent" />

	<Test name="Default">
		<Agent ref="TheAgent"/>

		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex"/>
	</Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug NumberExample4.xml

[*] Test 'Default' starting with random seed 61690.
Peach.Core.MutationStrategies.RandomStrategy Iteration: Switch iteration, setting controlIteration and controlRecordingIteration.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Updating action to original data model
Peach.Core.Dom.Action Updating action to original data model
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(2 bytes)
00000000   E8 03                                              ??              <1>
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher output(2 bytes)
00000000   E8 03                                              ??              <2>
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
<1> The value 1000
<2> The value 1000, having been defined in hex as 0x03e8

Notice that the `valueType` of `"string"` represents a number. This
number may be changed by endian-ness. Observe that the numeric value
was entered as 0x03e8, but Peach output the bytes 0xE8 and 0x03. The
value was converted to little endian before being output.

To assign a value as if copied directly from a hex editor we can use 
the `"hex"` `valueType`. Values entered in `"hex"` are output exactly as input 
regardless of endian-ness, as shown in the previous example that exercises  the `endian` attribute.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">

	<DataModel name="NumberExample5">
		<Number name="MyValue" value="AB CD" valueType="hex" size="16" signed="false" />
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="NumberExample5"/>
			</Action>
		</State>
	</StateModel>

	<Agent name="TheAgent" />

	<Test name="Default">
		<Agent ref="TheAgent"/>

		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex"/>
	</Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug NumberExample5.xml

[*] Test 'Default' starting with random seed 55408.
Peach.Core.MutationStrategies.RandomStrategy Iteration: Switch iteration, setting controlIteration and controlRecordingIteration.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Updating action to original data model
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(2 bytes)
00000000   AB CD                                              ??              <1>
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
<1> The value is 43981.
==========================
