<<<
[[Stream]]
== Stream

_Streams_ are logical blocks of data that contain other data blocks (such as zip and audio/video [A/V] multimedia files). _Stream_ elements are used to represent streams in a single model. 

Like xref:Block[Block] elements, _Stream_ elements allow groupings of one or more data elements in a logical structure, in this case to represent the content of the stream. 

_Stream_ elements have two additional pieces of metadata that _Blocks_ lack, a stream name and a stream attribute. Stream-aware publishers can use the metadata and content to combine all streams in a data model into a single file. A single data model representing a zip file would use the _Stream_ element to represent each file that makes up the zip file.

_Stream_ is a child element of either xref:DataModel[DataModel] or xref:Block[Block].

The xref:Publishers_Zip[Zip] publisher looks for Stream elements and creates a zip archive of all the streams in a model.

IMPORTANT: Zip is the only Peach-supplied publisher aware of _Stream_ elements. If you wish to fuzz an A/V file, you will need to create your own publisher.

=== Syntax

[source,xml]
----
<Stream streamName="TheStream">
  <String value="Hello world!" />
</Block>
----

=== Attributes

_Required:_

streamName:: Name of the underlying stream

_Optional:_

xref:name[name]:: Name of the stream element.
xref:ref[ref]:: Reference to a xref:DataModel[DataModel_Stream] to use as a template.
xref:length[length]:: Data element length.
xref:lengthType[lengthType]:: The unit of measure for the length attribute. The default value is bytes.
xref:constraint[constraint]:: Scripting expression that evaluates to true or false. Default is null.

xref:minOccurs[minOccurs]::
	The minimum number of times this element must occur. Defaults to 1.  +
	* Used to define arrays with variable size. Arrays defined by min/maxOccurs generally have a relation
	defined.
	* Adding this attribute, even with a value of 1, converts the element to an array.

xref:maxOccurs[maxOccurs]::
	The maximum number of times this element can occur. Defaults to 1.  +
	* Used to define arrays with static size.
	* Adding this attribute, even with a value of 1, converts the element to an array.

xref:occurs[occurs]::
	Actual occurrences of element. Defaults to 1.  +
	* Used to define arrays with static size.
	* Adding this attribute, even with a value of 1, converts the element to an array.

xref:mutable[mutable]:: Is this data element changeable (should it be mutated), defaults to false.
streamAttribute:: Integer representing any underlying attribute of a stream, defaults to 0.

=== Child Elements

xref:Analyzers[Analyzer]:: Analyzes current element post cracking, can dynamically change model.
xref:Blob[Blob]:: Represents binary data (array of bytes) to create simple dumb fuzzers in Peach.
xref:Block[Block]:: Groups one or more data elements in a logical structure.
xref:Choice[Choice]:: Indicates all sub-elements are valid; but only one sub-element should be selected.
xref:Fixup[Fixup]:: Perform dynamic transformations such as checksums and CRCs.
xref:Flags[Flags]:: Defines a set of bit sized flags.
xref:Hint[Hint]:: Provides information to mutators.
xref:Number[Number]:: Defines a binary number of arbitrary bit size.
xref:Padding[Padding]:: Pads variably sized blocks or data models for uniformity and consistency.
xref:Placement[Placement]:: Relocates an element after it has been cracked.
xref:Transformer[Transformer]:: Performs static transformations such as compression or encoding.
xref:XmlElement[XmlElement]:: Defines an XML element, the basic building block of XML documents.

=== Mutators

The following mutators operate on this element type:


_Enabled when element is marked as an array_

xref:Mutators_ArrayNumericalEdgeCasesMutator[ArrayNumericalEdgeCasesMutator]:: This mutator grows and shrinks an array to counts based on numerical edge cases.
xref:Mutators_ArrayRandomizeOrderMutator[ArrayRandomizeOrderMutator]:: This mutator randomizes the order of items in an array.
xref:Mutators_ArrayReverseOrderMutator[ArrayReverseOrderMutator]:: This mutator reverses the order of items in an array.
xref:Mutators_ArrayVarianceMutator[ArrayVarianceMutator]:: This mutator grows and shrinks an array to a variance of counts based on the current size.

_Used for all data elements_

xref:Mutators_DataElementBitFlipper[DataElementBitFlipper]:: This mutator produces test cases by flipping bits in the output value.
xref:Mutators_DataElementDuplicate[DataElementDuplicate]:: This mutator duplicates data elements.
xref:Mutators_DataElementRemove[DataElementRemove]:: This mutator removes data elements.
xref:Mutators_DataElementSwapNear[DataElementSwapNear]:: This mutator swaps data elements.
xref:Mutators_SampleNinjaMutator[SampleNinjaMutator]:: This mutator combines data elements from different data sets.

_Enabled when element is part of a size relation_

xref:Mutators_SizedDataEdgeCase[SizedDataEdgeCase]:: This mutator causes the data portion of a relation to be sized as numerical edge cases.
xref:Mutators_SizedDataVariance[SizedDataVariance]:: This mutator causes the data portion of a relation to be sized as numerical variances.
xref:Mutators_SizedEdgeCase[SizedEdgeCase]:: This mutator changes both sides of the relation (data and value) to match numerical edge cases.
xref:Mutators_SizedVariance[SizedVariance]:: This mutator changes both sides of the relation (data and value) to match numerical variances of the current size.


=== Background

The Stream element is very similar to the xref:Block[Block] element, except the Stream element includes two pieces of additional data: the streamName and the streamAttribute.

Conceptually, the following Stream and Block examples are very similar to one another. 

Stream example:

[source,xml]
----
<Stream name="TheStream" streamName="file1.txt" streamAttribute="100">
  <String value="Hello World"/>
  <Transformer class="Base64Encode"/>
</Stream>
----

Block example (compare this with the previous Stream definition):

[source,xml]
----
<Block name="TheStream">
  <String name="Name" value="file1.txt"/>
  <Number name="Attribute" size="32" signed="false" value="100"/>
  <Block name="Content">
    <String value="Hello World"/>
    <Transformer class="Base64Encode"/>
  </Block>
</Block>
----

The stream name, attribute and children all support fuzzing.

Additionally, relations and fixups can reference children of different streams.

The Stream element is intended for use by publishers that are stream aware (such as xref:Publishers_Zip[Zip]). If the publisher is not stream aware, the stream element is treated exactly like a xref:Block[Block].

=== Examples

.Stream with xref:Publishers_Zip[Zip] publisher
==========================
The following definition produces a zip file containing a single entry 'file1.txt' containing the string 'Hello World'.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="StreamExample1">
    <Stream streamName="file1.txt">
      <String value="Hello World"/>
    </Stream>
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="output">
        <DataModel ref="StreamExample1" />
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>

    <Publisher class="Zip">
      <Param name="FileName" value="fuzzed.zip" />
    </Publisher>
  </Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug example.xml

[*] Test 'Default' starting with random seed 59388.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Enterprise.Publishers.ZipPublisher start()
Peach.Enterprise.Publishers.ZipPublisher open()
Peach.Enterprise.Publishers.ZipPublisher Added 1 entries to zip file.
Peach.Enterprise.Publishers.ZipPublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Enterprise.Publishers.ZipPublisher stop()

[*] Test 'Default' finished.

----
==========================

.Stream with xref:Publishers_ConsoleHex[ConsoleHex] publisher
==========================
Streams are treated like blocks when used with publishers that are not stream aware.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="StreamExample2">
    <Stream streamName="file1.txt">
      <String value="Hello World"/>
    </Stream>
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="output" publisher="ConsolePub">
        <DataModel ref="StreamExample2" />
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>

    <Publisher class="ConsoleHex" name="ConsolePub"/>
  </Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug example.xml

[*] Test 'Default' starting with random seed 30169.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(11 bytes)
00000000   48 65 6C 6C 6F 20 57 6F  72 6C 64                  Hello World
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
==========================

.Multiple streams
==========================
Produce a zip file containing multiple files.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach ../peach.xsd">

  <DataModel name="StreamExample3">
    <Stream streamName="file1.txt">
      <String value="Root file one"/>
    </Stream>
    <Stream streamName="dir/file1.txt">
      <String value="File one in subdirectory"/>
    </Stream>
    <Stream streamName="dir/file2.txt">
      <String value="File two in subdirectory"/>
    </Stream>
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="output">
        <DataModel ref="StreamExample3" />
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>

    <Publisher class="Zip">
      <Param name="FileName" value="fuzzed.zip" />
    </Publisher>
  </Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug example.xml

[*] Test 'Default' starting with random seed 58326.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Enterprise.Publishers.ZipPublisher start()
Peach.Enterprise.Publishers.ZipPublisher open()
Peach.Enterprise.Publishers.ZipPublisher Added 3 entries to zip file.
Peach.Enterprise.Publishers.ZipPublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Enterprise.Publishers.ZipPublisher stop()

[*] Test 'Default' finished.
----

Contents of produced +fuzzed.zip+

----
> unzip -l fuzzed.zip
Archive:  fuzzed.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
       13  04-09-2014 18:14   file1.txt
       24  04-09-2014 18:14   dir/file1.txt
       24  04-09-2014 18:14   dir/file2.txt
---------                     -------
       61                     3 files
----

==========================
