<<<
[[VarNumber]]
== VarNumber

The _VarNumber_ element defines a variable width binary number of any arbitrary bit size from 1 to 64. Binary numbers are packed into a byte representation with a byte order of little-endian or big-endian.

_VarNumber_ is similar to xref:Number[Number] except the size is not hard coded and instead is driven by a method such as a size-of relation or limit of available data. 

The _VarNumber_ element should not be used for character-based numbers, or ASCII numbers. Instead, use a xref:String[String] element.

See also xref:Number[Number].

NOTE: While Peach supports unaligned data structures, using unaligned data incurs a performance penalty. The penalty stems from bit slicing that occurs behind the scenes.

=== Syntax

[source,xml]
----
<Number name="SizeOfAlmondsNumber" size="4" endian="big" signed="false">
    <Relation type="size" of="Almonds" />
</Number>

<VarNumber name="Almonds" endian="big" signed="false" />
----

=== Attributes

_Required:_

No required attributes.

_Optional:_

xref:name[name]::
	Name of the number.
xref:value[value]::
	The default value to assign to the number.
xref:valueType[valueType]::
	The representation of the value. Valid options are string and hex.
xref:token[token]::
	This element is treated as a token when parsing. Valid values are true and false, defaults to false.
xref:endian[endian]::
	Byte order of the number. Valid options are big, little, and network. Network is an alias for big. The default value is little.
xref:signed[signed]::
	The number is signed or unsigned. Valid values are true and false, defaults to false.
xref:constraint[constraint]::
	A constraint in the form of a python expression. Used during data cracking.
xref:mutable[mutable]::
	Is data element changeable (should it be mutated during fuzzing). Valid values are true and false, defaults to true.

xref:minOccurs[minOccurs]::
	The minimum number of times this element must occur. Defaults to 1.  +
	* Used to define arrays with variable size. Arrays defined by min/maxOccurs generally have a relation
	defined.
	* Adding this attribute, even with a value of 1, converts the element to an array.

xref:maxOccurs[maxOccurs]::
	The maximum number of times this element can occur. +
	* Used to define arrays with static size.
	* Adding this attribute, even with a value of 1, converts the element to an array.

xref:occurs[occurs]::
	Actual occurrences of element. Defaults to 1.  +
	* Used to define arrays with static size.
	* Adding this attribute, even with a value of 1, converts the element to an array.

=== Child Elements

xref:Analyzers[Analyzer]:: Analyzes current element post cracking, can dynamically change model.
xref:Fixup[Fixup]:: Performs dynamic transformations such as checksums and CRCs.
xref:Hint[Hint]:: Provides information to mutators.
xref:Placement[Placement]:: Relocates an element after it has been cracked.
xref:Relation[Relation]:: Identifies a type of relationship with another data element (such as count).
xref:Transformer[Transformer]:: Performs static transformations such as compression or encoding.

=== Mutators

The following mutators operate on this element type:

_Enabled when element is marked as an array_

xref:Mutators_ArrayNumericalEdgeCasesMutator[ArrayNumericalEdgeCasesMutator]:: This mutator grows and shrinks an array to counts based on numerical edge cases.
xref:Mutators_ArrayRandomizeOrderMutator[ArrayRandomizeOrderMutator]:: This mutator randomizes the order of items in an array.
xref:Mutators_ArrayReverseOrderMutator[ArrayReverseOrderMutator]:: This mutator reverses the order of items in an array.
xref:Mutators_ArrayVarianceMutator[ArrayVarianceMutator]:: This mutator grows and shrinks an array to a variance of counts based on the current size.

_Used for all data elements_

xref:Mutators_DataElementBitFlipper[DataElementBitFlipper]:: This mutator produces test cases by flipping bits in the output value.
xref:Mutators_DataElementDuplicate[DataElementDuplicate]:: This mutator duplicates data elements.
xref:Mutators_DataElementRemove[DataElementRemove]:: This mutator removes data elements.
xref:Mutators_DataElementSwapNear[DataElementSwapNear]:: This mutator swaps data elements.
xref:Mutators_SampleNinjaMutator[SampleNinjaMutator]:: This mutator combines data elements from different data sets.

_Enabled when element is part of a size relation_

xref:Mutators_SizedDataEdgeCase[SizedDataEdgeCase]:: This mutator causes the data portion of a relation to be sized as numerical edge cases.
xref:Mutators_SizedDataVariance[SizedDataVariance]:: This mutator causes the data portion of a relation to be sized as numerical variances.
xref:Mutators_SizedEdgeCase[SizedEdgeCase]:: This mutator changes both sides of the relation (data and value) to match numerical edge cases.
xref:Mutators_SizedVariance[SizedVariance]:: This mutator changes both sides of the relation (data and value) to match numerical variances of the current size.

_Specific to this element type_

xref:Mutators_ExtraValues[ExtraValues]:: This mutator provides extra test case values on a per-data element basis.

xref:Mutators_NumberEdgeCase[NumberEdgeCase]:: This mutator produces numerical edge cases for integer values.
xref:Mutators_NumberRandom[NumberRandom]:: This mutator produces random values from the available numerical space.
xref:Mutators_NumberVariance[NumberVariance]:: This mutator produces values near the current value of a number.


=== Examples

.Simple VarNumber Example
==========================

Output with different values in a _VarNumber_ element to show how the encoded expands as needed.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach	xmlns="http://peachfuzzer.com/2012/Peach" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://peachfuzzer.com/2012/Peach /peach/peach.xsd">
		
	<DataModel name="TheDataModel">
	
		<Number name="NumLength" size="8">
			<Relation type="size" of="Almonds"/>
		</Number>
		
		<VarNumber name="Almonds" value="32000" />
		
	</DataModel>

	<StateModel name="TheState" initialState="Initial">
		<State name="Initial">
			<Action type="output">
				<DataModel ref="TheDataModel"/>
				<Data>
					<Field name="Almonds" value="1"/> <1>
				</Data>
			</Action>
			
			<Action type="output">
				<DataModel ref="TheDataModel"/>
				<Data>
					<Field name="Almonds" value="32000"/> <2>
				</Data>
			</Action>
			
			<Action type="output">
				<DataModel ref="TheDataModel"/>
				<Data>
					<Field name="Almonds" value="3200000"/> <3>
				</Data>
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex"/>
	</Test>
</Peach>
----
<1> First output should produce 1 byte for the size and 1 byte for the number
<2> Second output should produce 1 byte for the size and 2 bytes for the number
<3> Third output should produce 1 byte for the size and 3 bytes for the number

Output from this example:

----
>peach -1 --debug NumberExample1.xml

[*] Web site running at: http://10.0.1.87:8888/

[*] Test 'Default' starting with random seed 56906.
2016-07-08 16:38:47.6099 Peach.Pro.Core.Loggers.JobLogger Writing debug.log to: c:\peach-pro\output\win_x64_debug\bin\Logs\example.xml_20160708163846\debug.log

[R1,-,-] Performing iteration
2016-07-08 16:38:47.7699 Peach.Core.Engine runTest: Performing control recording iteration.
2016-07-08 16:38:47.8159 Peach.Core.Dom.StateModel Run(): Changing to state "Initial".
2016-07-08 16:38:47.8259 Peach.Core.Dom.Action Run(Action): Output
2016-07-08 16:38:47.9450 Peach.Pro.Core.Publishers.ConsolePublisher start()
2016-07-08 16:38:47.9450 Peach.Pro.Core.Publishers.ConsolePublisher open()
2016-07-08 16:38:47.9450 Peach.Pro.Core.Publishers.ConsolePublisher output(2 bytes) <1>
00000000   01 01                                              .. 
2016-07-08 16:38:47.9550 Peach.Core.Dom.Action Run(Action_1): Output
2016-07-08 16:38:47.9550 Peach.Pro.Core.Publishers.ConsolePublisher output(3 bytes) <2>
00000000   02 7D 00                                           .}.
2016-07-08 16:38:47.9550 Peach.Core.Dom.Action Run(Action_2): Output
2016-07-08 16:38:47.9550 Peach.Pro.Core.Publishers.ConsolePublisher output(4 bytes) <3>
00000000   03 30 D4 00                                        .0..
2016-07-08 16:38:47.9550 Peach.Pro.Core.Publishers.ConsolePublisher close()
2016-07-08 16:38:47.9550 Peach.Core.Engine runTest: context.config.singleIteration == true
2016-07-08 16:38:47.9677 Peach.Pro.Core.Publishers.ConsolePublisher stop()
2016-07-08 16:38:47.9677 Peach.Core.Engine EndTest: Stopping all agents and monitors

[*] Test 'Default' finished.
----
<1> Value of '1' encoded as a single byte
<2> Value of '32000' using two bytes
<3> Value of '3200000' using three bytes

==========================
