#!/usr/bin/env python

deps = [
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
	'Peach.Core.dll',
	'Peach.Pro.dll',
]

pkgs = [
	'NDesk.DBus',
]

bld(
	name = 'Peach.Pro.Test.Bluetooth.exe',
	features = 'cs paket',
	use = deps,
	use_packages = pkgs,
	paket_settings = dict(
		frameworks = [
			'lib',
		],
	),
	source = bld.path.ant_glob('**/*.cs'),
	csdoc = False,
)
