=== Smart Fuzzing

Smart fuzzers are a class of fuzzers that operate with some knowledge and understanding of the target, and of the data being consumed. The amount of knowledge depends on the fuzzer being used.

A typical smart fuzzer does the following things:

* Understand the data format being consumed by the target application
* Monitor the target for fault conditions
* Modify the data to gain better coverage or to increase the ability to detect certain types of issues

Data understanding includes:

* Type information (string, integer, byte array)
* Relationships between fields in the data (length, offset, count)
* Ability integrity fields such as a checksum or a CRC

At this level, understanding the data structures and data types allows the fuzzer to make more informed changes (mutations) to the data. Smart fuzzers use this understanding level to find more bugs.

Smart fuzzers can control and monitor the fuzzing environment. Environment and instrumentation controls start all the components of the system so they are ready to fuzz. On a faulting condition, they reset the environment to a known, good state. Smart fuzzers can detect a faulting condition and collect any interesting data in the system at the time of the fault (including output from a debugger, a network capture, or files on the file system), and log the data for later review. High-quality smart fuzzers can run unattended for long periods of time and capture enough information to allow a resource to reasonably reproduce and investigate the faults that occurred.

Smart fuzzers also perform bug bucketing and basic risk analysis. Fuzzing commonly finds the same
issue multiple times during a long test session. Bucketing is an industry term for cataloging similar, and
possible duplicate, issues into a "bucket". Bucketing is typically done at a major and minor level.

* Major differences are generally distinct issues. The bucket for a major issue might associate
with a specific processor family, operating system, or monitor name.
* Minor differences that generate faults mean that the issues might be identical, or are
probably similar; yet, issues in minor buckets are worth reviewing to ensure the issues
have the same root cause.

Along with buckets, initial risk analysis allows you to direct your attention first on higher risk faults before spending time on lower risk issues. Risk analysis is not always possible, but is useful when it can be performed.

// For an example of building a smart fuzzer with Peach, see the xref:TutorialFileFuzzing[smart file fuzzing tutorial.]
// end
