#!/usr/bin/env python

deps = [
	'Peach.Core.dll',
	'Peach.Core.Test.dll',
	'Peach.Pro.dll',
	'Peach.Pro.WebApi2.dll',
	'System.dll',
	'System.Core.dll',
	'System.Net.Http.dll',
]

pkgs = [
	'Autofac',
	'Microsoft.AspNet.WebApi.Core',
	'Microsoft.Owin.Testing',
	'Moq',
	'NUnit',
]

bld(
	name = 'Peach.Pro.Test.WebApi.exe',
	features = 'cs test paket',
	use = deps,
	use_packages = pkgs,
	paket_settings = dict(
		frameworks = ['net45', 'net40'],
	),
	source = bld.path.ant_glob('**/*.cs'),
	csdoc = False,
)
