#!/usr/bin/env python

deps = [
	'Peach.Core.dll',
	'Peach.Pro.dll',
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
	'Facades/System.Runtime.dll',
	'Facades/System.Collections.dll',
]

pkgs = [
	'NLog',
	'NUnit',
	'DiffPlex',
]

bld(
	name = 'Peach.Pro.PitTester.dll',
	features = 'cs paket',
	use = deps,
	use_packages = pkgs,
	paket_settings = dict(
		frameworks = [
			'net45',
			'netstandard1.0'
		],
		excludes = [
			'Microsoft.CodeAnalysis.Analyzers',
			'NETStandard.Library',
			'System.Diagnostics.Contracts',
		],
	),
	source = bld.path.ant_glob('**/*.cs'),
)
