
=== Additional Resources

More information about Peach is available on the Web:

* http://peachfuzzer.com[Peach Fuzzer website]
* http://www.peachfuzzer.com/products/peach-pits/[Current Pits and Pit Packs]
* https://forums.peachfuzzer.com[Peach User Forums]
* https://vimeo.com/148176046[Installing Peach Fuzzer Software video]

=== Bug Reporting Guidelines

Support for Peach Fuzzer is available in two ways:

 * The Peach Forums site
 * Using the Peach ticketing system to open a support ticket

[[Peach_Forums]]
==== Peach Forums

There are two sets of forums for Peach, the community forums and the professional forums. Both forums are hosted at https://forums.peachfuzzer.com.

{product} users should access the private forums to receive support for the commercial versions of Peach. Responses on the commercial forums are prioritized over the public community forums.

To access the {product} forums, follow these steps:

. Register an account on the forums site.
. Send an email to support@peachfuzzer.com with your license email and forum username.
. Your account will be granted access to the commercial forums within 24 business hours.

Forums are monitored by the team at Peach Fuzzer, LLC; however, there is no guarantee of response time.

==== Support Tickets

You can open a support ticket by sending an email to _support@peachfuzzer.com_. You will receive an initial response within 24 business hours of opening the ticket. Peach support is available Monday through Friday. Peach support is not currently available on weekends or holidays.

When opening a ticket, please provide the following information in your email:

 * Operating system(s) in use by Peach and any agents
 * Exact version of Peach being used. This is available from the console output and in the _status.txt_ log file
 * Detailed description of the issue and expected behavior
 * Console output using the _--trace_ argument
 * (if possible) the full Pit file and configuration files

// end
