#!/usr/bin/env python

import os
from waflib import Task

deps = [
	'Peach.Core.dll',
	'Peach.Pro.dll',
	'Peach.Pro.WebApi2.dll',
	'System.dll',
	'System.Core.dll',
	'System.Xml.dll',
]

top = bld.path.parent.parent

def glob_from(*parts):
	path = os.path.join(*parts)
	return (
		top.find_or_declare(path),
		top.ant_glob(os.path.join(path, '**'))
	)

python_stdlib = glob_from('3rdParty', 'IronPython.StdLib.2.7.5', 'content')

makexsd = '%s PitTool.exe makexsd' % bld.env.RUN_NETFX

app = bld(
	name = 'Peach.exe',
	features = 'cs',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	# mkbundle = True,
	ver_product = 'Peach Fuzzing Platfom',
	install_644 = {
		python_stdlib[0] : python_stdlib[1],
		bld.path : bld.path.ant_glob('Plugins/* pits/* PCANBasic_NET.dll.config'),
	},
	ide_content = bld.path.ant_glob('samples/**/*'),
	ide_custom_commands = [
		dict(type='AfterBuild', command=makexsd, workingdir='${TargetDir}'),
	]
)

# samples folder is installed to output dir by ../SDK/wscript_build

if bld.env.MCS and bld.env.DEST_OS != 'win32':
	app.install_755 = 'peach'

common = [
	# Peach
	'Peach.exe',
	'PeachAgent.exe',
	'Peach.Pro.Web',
	'PitTool.exe',
	'sqlite3',

	# Include sample programs so sample pits work
	'SimpleHttpServer',
	'CrashableServer',
	'CrashingFileConsumer',
	'CrashingProgram',
	'ComTest',

	# Common side-process helpers
	'PeachTrampoline.exe',

	# Windows side-process helpers
	'Peach.Pro.ComContainer.exe',

	'VMware-VIX',        # VMWare VIX API
	'CrashWrangler',
]

peach_pro = common + [
	# Helper Programs
	'PeachValidator.exe',
	'PeachMinset.exe',

	# PCAP to pit tool
	'PeachPcapTool.exe',

	# CAN Recorder
	'PeachCanRecorder.exe',
	'PeachCanDbViewer.exe',

	# UI Web Recorder tool
	'PeachWebRecorder.exe',

	# Basic Block Pin Tool
	'pin',               # Pin Binaries
	'bblocks',
	'bblocks32',
	'bblocks64',
]

internal = common + [
	# Internal pit testing tools
	'CrashTest',
	'CrashTestDummy.exe',
	'nunit-console',
	'nunit-tools',
	'PeachWorker.exe',
	'PeachService.exe',
	'Peach.Core.Test.dll',
	'Peach.Pro.Test.dll',
	'Peach.Pro.Test.OS.Linux.dll',
	'Peach.Pro.Test.OS.OSX.dll',
	'Peach.Pro.Test.OS.Windows.dll',
	'Peach.Pro.Test.WebApi.exe',
	'UseAfterFree',
]

bld(
	features = 'peach zip',
	name = '-'.join([ 'peach-pro', bld.env.BUILDTAG, bld.variant ]),
	use = peach_pro,
)

internal_variant = bld.variant \
	.replace('debug', 'internal') \
	.replace('release', 'internal')

bld(
	features = 'peach zip',
	name = '-'.join([ 'peach-pro', bld.env.BUILDTAG, internal_variant ]),
	use = internal,
)
