#!/usr/bin/env python

deps = [
	'Peach.Core.dll',
	'Peach.Pro.dll',
	'System.Runtime.Remoting.dll',
	'System.dll',
	'System.Management.dll',
	'System.Xml.dll',
	'System.Core.dll',
	'System.Data.dll',
]

pkgs = [
	'NLog',
]

bld(
	name='Peach.Pro.ComContainer.exe',
	features = 'cs',
	use = deps,
	use_packages = pkgs,
	paket_settings = dict(
		frameworks = ['net45'],
	),
	source = bld.path.ant_glob('**/*.cs'),
)
