<<<
[[Fixups_CiscoFixup]]
== CiscoCdpChecksum

// Reviewed:
//  - 02/18/2014: Seth & Adam: Outlined
// Expand description to include use case "This is used when fuzzing {0} protocols"
// Show example of output
// Give full pit to run using hex publisher
// List Parent element types

// Updated:
// 2/21/14: Mick
// expanded description
// Added parent types
// Added full example

_CiscoCdpChecksum_ is a Custom Peach algorithm to fix  Cisco's one-off error in their CRC implementation (known feature).
It is defined in RFC1071.
It can be found in the Open source CRCTool Library.
This fixup is used when fuzzing protocols perform the Cisco implementation of CRC.

=== Parent Elements

xref:Number[Number]
xref:String[String]

=== Parameters

xref:ref[ref]:: Reference to the input data element used in the CRC calculation.

=== Examples

.Basic Usage Example
======================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

	<DataModel name="NoCrcPacket">
		<Number name="SrcPort"  size="16" endian="big" value="1234"/>
		<Number name="DestPort" size="16" endian="big" value="1235"/>
		<Number name="Length"   size="16" endian="big">
			<Relation type="size" of="NoCrcPacket"/>
		</Number>
		<Number name="checksum" size="16">
		</Number>
	</DataModel>

	<DataModel name="Packet">
		<Number name="SrcPort"  size="16" endian="big" value="1234"/>
		<Number name="DestPort" size="16" endian="big" value="1235"/>
		<Number name="Length"   size="16" endian="big">
			<Relation type="size" of="Packet"/>
		</Number>
		<Number name="checksum" size="16">
			<Fixup class="CiscoFixup">
				<Param name="ref" value="Packet" />
			</Fixup>
		</Number>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<Action type="output">
				<DataModel ref="NoCrcPacket" />
			</Action>

			<Action type="output">
				<DataModel ref="Packet" />
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex" />
	</Test>
</Peach>
----

Output from this example.

----
>peach -1 --debug example.xml

[*] Test 'Default' starting with random seed 26396.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Binding Error, unable to resolve binding 'Packet' attached to 'NoCrcPacket.Length'.
Peach.Core.Dom.SizeRelation Error, Of returned null
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(8 bytes)
00000000   04 D2 04 D3 00 08 00 00                            ???????? <1>
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher output(8 bytes)
00000000   04 D2 04 D3 00 08 52 F6                            ??????R? <2>
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----

<1> Output without CiscoFixup. Last two bytes are zero.
<2> Output with CiscoFixup. Last two bytes are a valid CRC for the packet.

======================
