<<<
[[Fixups_SequenceRandomFixup]]
== SequenceRandom

// Reviewed:
//  - 02/18/2014: Seth & Adam: Outlined
// Expand description to include
//   Use case "This is used when fuzzing {0} protocols"
//   Will return number within valid range of parent number
// Give full pit to run using hex publisher, test works
// List Parent element types
// Number, String

// Updated:
// - 02/18/2014: Mick
// Added full examples

The _SequenceRandom_ fixup produces a random integer each iteration.
This is useful when a field must be a unique value every iteration.

This checksum can be used when fuzzing protocols that contain a nonce or pseudo-random sequence number.
The RNG uses the same seed as Peach, so values produced are reproducible by setting the seed via the command line.

NOTE: SequenceRandom does not protect duplicate values from occurring.

=== Parent Elements

xref:Number[Number]
xref:String[String]

=== Parameters

This fixup does not support any parameters.

=== Examples

.Example of SequenceRandom Fixup
================================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

	<DataModel name="Packet">
		<Number name="SrcPort"  size="16" endian="big" value="1234"/>
		<Number name="DestPort" size="16" endian="big" value="1235"/>
		<Number name="Length"   size="16" endian="big">
			<Relation type="size" of="Packet"/>
		</Number>
		<Number name="Nonce" size="16" endian="big">
			<Fixup class="SequenceRandomFixup" />
		</Number>
	</DataModel>

	<StateModel name="TheState" initialState="initial">
		<State name="initial">
			<Action type="output">
				<DataModel ref="Packet" />
			</Action>
		</State>
	</StateModel>

	<Test name="Default">
		<StateModel ref="TheState"/>

		<Publisher class="ConsoleHex" />
	</Test>
</Peach>
----

Output of this example.

----
>peach -1 --debug example.xml

[*] Test 'Default' starting with random seed 24885.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(8 bytes)
00000000   04 D2 04 D3 00 08 93 F9                            ????????
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
================================
