<<<
[[Fixups_SHA384Fixup]]
== Sha384

// Reviewed:
//  - 02/18/2014: Seth & Adam: Outlined
// Expand description to include use case "This is used when fuzzing {0} protocols"
// Give full pit to run using hex publisher, test works
// List Parent element types can be applied to
// Blob

// Updated:
// - 02/18/2014: Mick
// Added full examples

Performs an SHA-384 hash of value of the reference element and places the result in the parent element. This is used when fuzzing protocols that hash data with SHA-384.

The SHA384 algorithm is defined in US Federal Information Processing Standard (FIPS) PUB 180-4 and is implemented in .Net Framework Implementation - System.Security.Cryptography.

=== Parent Elements

xref:String[String]
xref:Blob[Blob]

=== Parameters

xref:ref[ref]:: Reference to the input data element used in the hash calculation.

=== Examples

.Basic Sha384 Example
==========================
[source,xml]
----
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="Packet">
    <Block name="Header">
      <Number name="SrcPort"  size="16" endian="big" value="1234"/>
      <Number name="DestPort" size="16" endian="big" value="1235"/>
      <Number name="Length"   size="16" endian="big">
        <Relation type="size" of="Packet"/>
      </Number>
    </Block>
    <Blob name="Checksum">
      <Fixup class="SHA384Fixup">
        <Param name="ref" value="Header"/>
      </Fixup>
    </Blob>
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="output">
        <DataModel ref="Packet"/>
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>

    <Publisher class="ConsoleHex"/>
  </Test>
</Peach>
----

Output of this example.

----
>peach -1 --debug example.xml

[*] Test 'Default' starting with random seed 22335.

[R1,-,-] Performing iteration
Peach.Core.Engine runTest: Performing recording iteration.
Peach.Core.Dom.Action Run: Adding action to controlRecordingActionsExecuted
Peach.Core.Dom.Action ActionType.Output
Peach.Core.Publishers.ConsolePublisher start()
Peach.Core.Publishers.ConsolePublisher open()
Peach.Core.Publishers.ConsolePublisher output(54 bytes)
00000000   04 D2 04 D3 00 36 20 74  77 0A 0F B0 5A F8 B0 6B   ?????6 tw???Z??k
00000010   BE FC 4C CC 83 1A 25 C5  E9 5B 02 F5 F7 E0 41 05   ??L???%??[????A?
00000020   77 FB 86 6F 02 40 CE 32  E5 46 85 74 7B A3 0C 70   w??o?@?2?F?t{??p
00000030   E6 67 7D 0B 74 5A                                  ?g}?tZ
Peach.Core.Publishers.ConsolePublisher close()
Peach.Core.Engine runTest: context.config.singleIteration == true
Peach.Core.Publishers.ConsolePublisher stop()

[*] Test 'Default' finished.
----
==========================
