<<<
[[Publishers_Http]]
== Http Publisher (Depricated)

This publisher is depricated, please see xref:Publishers_WebApi[WebApi publisher].

_Http_ publisher sends data over HTTP via a valid HTTP method type.

_Http_ supports the following features:

 * Authentication via Basic, Digest, or Windows integrated
 * Definable method type
 * Fuzzing and dynamic setting of headers (both key and value)
 * Fuzzing and dynamic setting of query strings
 * Optional cookie support
 * SSL

See also the xref:Publishers_WebApi[WebApi] publisher.

=== Syntax

[source,xml]
----
<Publisher class="Http">
    <Param name="Method" value="POST" />
    <Param name="Url" value="http://foo/user/create" />
</Publisher>
----

=== Parameters

_Required:_

Method:: HTTP Method type (like GET and POST)
Url:: URL of target

_Optional:_

BaseUrl:: Base URL is used by some authentication types
Username:: Username for authentication
Domain:: Domain for authentication
Cookies:: Enable cookie support. Defaults to true.
CookiesAcrossIterations:: Track cookies across iterations. Defaults to false.
FailureStatusCodes:: 
    Comma separated list of status codes that are failures causing current test case to stop.
    Defaults to: +400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,500,501,502,503,504,505+
FaultOnStatusCodes:: Comma separated list of status codes that are faults. Defaults to none.
Timeout:: How long to wait in milliseconds for data/connection. Defaults to 3,000.
IgnoreCertErrors:: Allow HTTPS regardless of cert status. Defaults to false.
Proxy::
    To use HTTP proxy, set the URL. Default is none. Example: +http://192.168.1.1:8080+. +
     +
    The publisher will not use the default system proxy.
    If a proxy is required it must be explicitly set via the publisher parameter. +
     +
    Please note that the host +localhost+ and IP 127.0.0.1 will bypass the provided proxy. This is a behavior hardcoded into the underlying http networking code. For a discussion of options to deal with this limitation see the following article: link:http://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/MonitorLocalTraffic[Fiddler - Monitoring Local Traffic].

=== Actions

xref:Action_call[call]::
	Special method names used to fuzz the query string or a specific header.  +
	Query;; Specify as the method name for a call action, the first parameter is the query string
	Header;; Specify as the method name for a call action, the first parameter is the header name, the second is the value

xref:Action_start[start]:: Implicit Action to start the Publisher.
xref:Action_stop[stop]:: Implicit Action to stop the Publisher.
xref:Action_open[open]:: Open and initialize the socket.
xref:Action_close[close]:: Close and clean up the socket.
xref:Action_output[output]:: Data sent via output is written to the open socket.
xref:Action_input[input]:: Data received via input is read from the open socket.

=== Scripting

The Http publisher exposes a public Headers dictionary that can be used to add/remove headers from Python scripting code.  See the xref:Publishers_WebApi[WebApi] publisher examples.

=== Examples

.HTTP POST Request
====================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="PostBody">
    <String name="Username" value="username=user"/>
    <String name="Comma" value=","/>
    <String name="Password" value="password=admin"/>
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="output">
        <DataModel ref="PostBody" />
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>
    <Publisher class="Http">
      <Param name="Method" value="POST" />
      <Param name="Url" value="http://foo/user/create" />
    </Publisher>
  </Test>
</Peach>
----
====================

.HTTP GET Request
====================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="TheDataModel">
     <Blob/>
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="input" >
          <DataModel ref="TheDataModel" />
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>
    <Publisher class="Http">
      <Param name="Method" value="GET" />
      <Param name="Url" value="http://foo/user/create" />
    </Publisher>
  </Test>
</Peach>
----
====================

.Fuzzing HTTP GET Request Query String
====================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

 <DataModel name="QueryModel">
   <String value="key"/>
   <String value="=" token="true" />
   <String value="value"/>
  </DataModel>

  <DataModel name="GetInputModel">
    <Blob/>
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="call" method="Query">
        <Param>
          <DataModel ref="QueryModel" />
        </Param>
      </Action>

      <Action type="input">
        <DataModel ref="GetInputModel"/>
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>
    <Publisher class="Http">
      <Param name="Method" value="GET" />
      <Param name="Url" value="http://foo/user/create" />
    </Publisher>
  </Test>
</Peach>
----
====================

.Fuzzing Cookie Value in Header
====================
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <DataModel name="HeaderKey">
   <String value="Cookie" />
  </DataModel>

  <DataModel name="HeaderValue">
     <String value="user=newuesr" />
  </DataModel>

  <DataModel name="GetInputModel">
    <Blob/>
  </DataModel>

  <StateModel name="TheState" initialState="initial">
    <State name="initial">
      <Action type="call" method="Header">
        <Param>
          <DataModel ref="HeaderKey" />
        </Param>
        <Param>
          <DataModel ref="HeaderValue" />
        </Param>
      </Action>

      <Action type="input">
        <DataModel ref="GetInputModel"/>
      </Action>
    </State>
  </StateModel>

  <Test name="Default">
    <StateModel ref="TheState"/>
    <Publisher class="Http">
      <Param name="Method" value="GET" />
      <Param name="Url" value="http://foo/user/create" />
    </Publisher>
  </Test>
</Peach>
----
====================
