<<<
[[Publishers_WebApi]]
== WebApi Publisher

The _WebApi_ Publisher  is an I/O adapter that communicates with various web API/HTTP end points.  This publisher is used with the xref:Action_web[web] action type.

This is the recommended method to perform web requests using Peach.  The +Rest+ and +Http+ publishers are depricated.

This publisher, in combination with the xref:Action_web[web] action gives full control over:

 * Path
 * Query string
 * Form data
 * Body
 ** Json
 ** XML
 ** Binary

Several analyzers are useful when building Pits for for use with this publisher:

xref:Analyzers_Json[Json]::
    Converts JSON documents or strings into Peach data models.
    Can be used both inside of DataModels with the String element or also via the command line.
    
xref:Analyzers_Postman[Postman]::
    Converts Postman Catalogs to Peach Pits.
    
xref:Analyzers_Swagger[Swagger]::
    Converts Swagger JSON to Peach Pits

xref:Analyzers_WebRecordProxy[WebRecordProxy]::
    Recording proxy captures web requests and generates full pit.
    This makes creating the base pit easy, simply use as your HTTP proxy.

xref:Analyzers_Xml[Xml]::
    Converts XML documents or string into Peach data models.
    Can be used both inside of DataModels with the String element or also via the command line.


TIP: SSL/TLS is supported, just use +https+ as the protocol in the URL.

=== Syntax

[source,xml]
----
<Publisher class="WebApi"/>
----

=== Parameters

_Required:_

There are no required parameters.

_Optional:_

BaseUrl:: The base URL to use for authentication. +
    Example: +http://myservice.domainname.example+. +
    This parameter is required if the +Username+ and +Password+ parameters are specified.
Username:: Username for authentication
Password:: Password for for authentication
Domain:: Domain for authentication

FailureStatusCodes:: 
    Comma separated list of status codes that are failures causing current test case to stop.
    Defaults to: +400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,500,501,502,503,504,505+

FaultOnStatusCodes:: Comma separated list of status codes that are faults. Defaults to none.
Timeout:: How long to wait in milliseconds for data/connection. the default value is 3,000.
IgnoreCertErrors:: Allow HTTPS regardless of cert status. The default value is true.

Proxy::
    To use HTTP proxy, set the URL. Default is none. Example: +http://192.168.1.1:8080+. +
     +
    The publisher will not use the default system proxy.
    If a proxy is required it must be explicitly set via the publisher parameter. +
     +
    Please note that the host +localhost+ and IP 127.0.0.1 will bypass the provided proxy. This is a behavior hardcoded into the underlying http networking code. For a discussion of options to deal with this limitation see the following article: link:http://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/MonitorLocalTraffic[Fiddler - Monitoring Local Traffic].


=== Actions

xref:Action_web[web]::
+
Web actions are used to perform WebApi calls.
+
This action provides full control over the HTTP request.
The 'method' attribute contains the HTTP method (GET, POST, etc.).
The 'url' attribute contains the URL with optional parameter substitution tokens.
These tokens are replaced with the parameters provided by the 'Path' elements.
+
* This example places a call that expects to receive a single parameter: +http://localhost/product/{id}+
* Query parameters are set using 'Query' elements.
+
This action also supports the xref:web_Response[Response] element to capture the response status code, headers and body.

=== Example

.Calling WebApi Services with Result
===================================

The following example provides three fragments using the GET and POST methods. 
For the GET request, the Result element is used to capture any returned data.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

<DataModel name="PostData">
    <JsonObject>
        <JsonString propertyName="Name" value="Widget" />
        <JsonDouble propertyName="Price" value="1.99" />
        <JsonInteger propertyName="Quantify" value="1" />
    </JsonObject>
</DataModel>

<DataModel name="WebApiResult">
	<Choice name="ResultOrEmpty">
		<String name="Result">
			<Analyzer class="Json" />
		</String>
		<Block name="Empty" />
	</Choice>
</DataModel>

<StateModel name="Default" initialState="FirstState">
    <State name="FirstState">
        <Action type="web" method="GET" url="http://www.example.com/product/{id}">
            <Path name="Id" key="id" value="1"/>

            <Response />
                <DataModel ref="WebApiResult" />
            </Response>
        </Action>

        <Action type="web" method="GET" url="http://www.example.com/invoices">
            <Query name="StartDate" key="start_date" value="11-21-2011" />
            <Query name="EndDate" key="end_date" value="11-21-2015" />

            <Response>
                <DataModel ref="WebApiResult" />
            </Response>
        </Action>

        <Action type="call" method="POST" url="http://www.example.com/product/{id}">
            <Path name="Id" key="id" value="100" />
            <Body name="PostData">
                <DataModel ref="PostData" />
            </Body>
        </Action>
    </State>
</StateModel>

<Test name="Default">
    <StateModel ref="Default" />
    <Publisher class="WebApi" />
</Test>

</Peach>
----

===================================


.Posting XML
===================================

The following example provides three fragments using the GET and POST methods.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

<DataModel name="PostData">
    <XmlElement elementName="Product">
        <XmlAttribute attributeName="Name">
            <String value="Widget" />
        </XmlAttribute>
        <XmlAttribute attributeName="Price">
            <String value="1.99" />
        </XmlAttribute>
        <XmlAttribute attributeName="Quantity">
            <String value="1" />
        </XmlAttribute>
    </XmlElement>
</DataModel>

<StateModel name="Default" initialState="FirstState">
    <State name="FirstState">

        <Action type="web" method="POST" url="http://www.example.com/product/{id}">
            <Path name="Id" key="id" value="1"/>

            <Body name="PostData">
                <DataModel ref="PostData" />
            </Body>
        </Action>
        
    </State>
</StateModel>

<Test name="Default">
    <StateModel ref="Default" />
    <Publisher class="WebApi" />
</Test>

</Peach>
----
===================================


.Posting Binary
===================================

The following example provides three fragments using the GET and POST methods.

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

<DataModel name="PostData">
    <Blob />
</DataModel>

<StateModel name="Default" initialState="FirstState">
    <State name="FirstState">

        <Action type="web" method="POST" url="http://www.example.com/product/{id}/image">
            <Path name="Id" key="id" value="1"/>
            <Body name="PostData">
                <DataModel ref="PostData" />
                <Data fileName="image.png" />
            </Body>
        </Action>
        
    </State>
</StateModel>

<Test name="Default">

    <StateModel ref="Default"/>
    <Publisher class="WebApi"/>

</Test>
</Peach>
----
===================================

.Setting Custom Header via Pit
===================================

The following example shows how to set a custom header via the Pit XML.
The custom header is named "X-CustomeHeader" with a value of "Hello World".

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

<StateModel name="Default" initialState="FirstState">
    <State name="FirstState">
	
        <Action type="web" method="GET" url="http://www.example.com/product/{id}">
            <Path name="Id" key="id" value="1"/>
            <Header name="x-custom" key="X-CustomHeader" value="Hello World!" />
            <Response/>
        </Action>
		
    </State>
</StateModel>

<Test name="Default">
    <StateModel ref="Default" />
    <Publisher class="WebApi" />
</Test>

</Peach>
----

===================================

.Setting Custom Authentication Header via Python
===================================

The following example shows how to add custom authentication via a python script.
In this example we will configure a pit for fuzzing an Amazon AWS S3 service endpoint.
This is only an example and should not actually be used to fuzz AWS.

[source,python]
----
import base64
import hmac
from hashlib import sha1
from email.Utils import formatdate

AWS_ACCESS_KEY_ID = "44CF9590006BF252F707"
AWS_SECRET_KEY = "OtxrzxIsfpFjA7SwPzILwy8Bw21TLhquhboDYROV"

def AwsAuthGen(context, action):

    # Get the Publisher (WebApiPublisher)
    if action.publisher:
        publisher = context.test.publishers[action.publisher]
    else:
        publisher = context.test.publishers[0]

    XAmzDate = formatdate()

    h = hmac.new(AWS_SECRET_KEY, "PUT\n\napplication/json\n\nx-amz-date:%s\n/?policy" % XAmzDate, sha1)
    authToken = base64.encodestring(h.digest()).strip()

    publisher.Headers.Add("x-amz-date", XAmzDate)
    publisher.Headers.Add("Authorization", "AWS %s:%s" % (AWS_ACCESS_KEY_ID, authToken))

# end
----

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<Peach xmlns="http://peachfuzzer.com/2012/Peach" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://peachfuzzer.com/2012/Peach peach.xsd">

  <Import import="aws_s3_example"/>
  
  <!--
{
"Version":"2008-10-17",
"Id":"aaaa-bbbb-cccc-dddd",
"Statement" : [
    {
        "Effect":"Allow",
        "Sid":"1", 
        "Principal" : {
            "AWS":["111122223333","444455556666"]
        },
        "Action":["s3:*"],
        "Resource":"arn:aws:s3:::bucket/*"
    }
 ] 
} 
  -->
  <!-- Generated using the JSON analyzer -->
  <DataModel name="Policy">
    <JsonObject>
      <JsonString propertyName="Version" name="Version" value="2008-10-17" />
      <JsonString propertyName="Id" name="Id" value="aaaa-bbbb-cccc-dddd" />
      <JsonArray propertyName="Statement" name="Statement">
        <JsonObject propertyName="Statement" name="Statement">
          <JsonString propertyName="Effect" name="Effect" value="Allow" />
          <JsonString propertyName="Sid" name="Sid" value="1" />
          <JsonObject propertyName="Principal" name="Principal">
            <JsonArray propertyName="AWS" name="AWS">
              <JsonString propertyName="AWS" name="AWS" value="111122223333" />
              <JsonString value="444455556666" />
            </JsonArray>
          </JsonObject>
          <JsonArray propertyName="Action" name="Action">
            <JsonString propertyName="Action" name="Action" value="s3:*" />
          </JsonArray>
          <JsonString propertyName="Resource" name="Resource" value="arn:aws:s3:::bucket/*" />
        </JsonObject>
      </JsonArray>
    </JsonObject>
  </DataModel>

  <StateModel name="TheStateModel" initialState="Initial">
    <State name="Initial">

      <Action type="web" method="PUT" url="http://XXXXX.s3.amazonaws.com/?policy"
              onStart="aws_s3_example.AwsAuthGen(context, action)">
            
        <Body name="Body">
          <DataModel ref="Policy" />
        </Body>
      </Action>
      
    </State>
  </StateModel>

  <Test name="Default" maxOutputSize="20000000">
    <StateModel ref="TheStateModel"/>
    <Publisher class="WebApi">
      <Param name="FaultOnStatusCodes" value="500,501,502,503,504,505" />
    </Publisher>
  </Test>
</Peach>
----

===================================


