#!/usr/bin/env python

deps = [
	'BouncyCastle.Crypto.dll',
	'Peach.Core.dll',
	'Peach.Core.Test.dll',
	'Peach.Pro.dll',
	'Peach.Pro.PitTester.dll',
	'Renci.SshNet.dll',
	'System.dll',
	'System.Configuration.dll',
	'System.Core.dll',
	'System.Data.dll',
	'System.Data.SQLite.dll',
	'System.Net.Http.dll',
	'System.Runtime.Remoting.dll',
	'System.Web.Services.dll',
	'System.Xml.dll',
]

pkgs = [
	'Dapper',
	'DotNetZip',
	'Mono.Posix-4.5',
	'Moq',
	'Newtonsoft.Json',
	'NLog',
	'NUnit',
	'SharpPcap',
	'SocketHttpListener',
]

frameworks = [
	'net45', 
	'Net45', 
	'portable-net45+dnxcore50+sl4+wp71+win8+wpa81', 
	'portable-net45+win8+wpa81',
	'net40',
	'net3.5-client', 
	'net20', 
	'net',
	'lib',
]

bld(
	name = 'Peach.Pro.Test.dll',
	features = 'cs test paket',
	use = deps,
	use_packages = pkgs,
	paket_settings = dict(
		frameworks = frameworks
	),
	source = bld.path.ant_glob('**/*.cs **/*.resx'),
	resource = bld.path.ant_glob('Resources/**/*'),
	ide_use = 'CrashingProgram CrashingFileConsumer CrashableServer CrashTest',
	namespace = 'Peach.Pro.Test.Core',
)
